ty = {}

--Lylibs--
ty.AutoRefImage = typeof(gs.AutoRefImage)
ty.AutoRefRawImage = typeof(gs.AutoRefRawImage)
ty.ImageFrame = typeof(gs.ImageFrame)
ty.AnimatCtrl = typeof(gs.AnimatCtrl)
ty.AnimatCall = typeof(gs.AnimatCall)
ty.ParticleHandle = typeof(gs.ParticleHandle)
ty.RichText = typeof(gs.RichText)
ty.BtnEx = typeof(gs.BtnEx)
ty.ProgressBar = typeof(gs.ProgressBar)
ty.ProgressBarHp = typeof(gs.ProgressBarHp)
ty.ProgressBarRole = typeof(gs.ProgressBarRole)
ty.ProgressBarLayers = typeof(gs.ProgressBarLayers)
ty.LyScroller = typeof(gs.LyScroller)
ty.ItemRender = typeof(gs.ItemRender)
ty.ChainLightning = typeof(gs.ChainLightning)
ty.ChatLoopVerticalScrollRect = typeof(gs.ChatLoopVerticalScrollRect)
ty.RadarProperty = typeof(gs.RadarProperty)
ty.LyNumberStepper = typeof(gs.LyNumberStepper)
ty.LyNumberStepperLongPress = typeof(gs.LyNumberStepperLongPress)
ty.LongPressOrClickEventTrigger = typeof(gs.LongPressOrClickEventTrigger)
ty.LongTimeComponent = typeof(gs.LongTimeComponent)
ty.LanText = typeof(gs.LanText)
ty.LyRawImage = typeof(gs.LyRawImage)
ty.MonoStrDict = typeof(gs.MonoStrDict)
ty.EffectPointSet = typeof(gs.EffectPointSet)
ty.CharAppendEffect = typeof(gs.CharAppendEffect)
ty.EffectFixSet = typeof(gs.EffectFixSet)
ty.EffectRandomSet = typeof(gs.EffectRandomSet)
ty.EffectRandomController = typeof(gs.EffectRandomController)
ty.EffectRandomMananger = typeof(gs.EffectRandomMananger)
ty.EffectForModelMaterial = typeof(gs.EffectForModelMaterial)
ty.EffectForPost = typeof(gs.EffectForPost)
ty.DynamicBoneController = typeof(gs.DynamicBoneController)
ty.ShakeObject = typeof(gs.ShakeObject)
ty.DrawCircle = typeof(gs.DrawCircle)
ty.EventClick = typeof(gs.EventClick)
ty.GoRefHandle = typeof(gs.GoRefHandle)
ty.AutoRimController = typeof(gs.AutoRimController)
ty.DragUI = typeof(gs.DragUI)
ty.ModelHeihgtGradient = typeof(gs.ModelHeihgtGradient)
ty.GoMouseEvent = typeof(gs.GoMouseEvent)
ty.RaycastMouseEvent = typeof(gs.RaycastMouseEvent)
ty.SmileController = typeof(gs.SmileController)
ty.ModelMaterials = typeof(gs.ModelMaterials)
ty.ReflectionTexture = typeof(gs.ReflectionTexture)
ty.RecruitDrag = typeof(gs.RecruitDrag)
ty.FixedDirection = typeof(CS.FixedDirection)
ty.LightRotate = typeof(CS.LightRotate)

ty.UIDrawLineComponent = typeof(gs.UIDrawLineComponent)
ty.StoryBGComponent = typeof(gs.StoryBGComponent)
ty.OutlineComponent = typeof(gs.OutlineComponent)
-- ty.FAnimationManager = typeof(gs.FAnimationManager)
ty.SimpleAnimation = typeof(gs.SimpleAnimation)
ty.FlipCameraComponent = typeof(gs.FlipCameraComponent)
ty.StoryEditorListenerManager = typeof(gs.StoryEditorListenerManager)
--ty.StoryModelUtilComponent = typeof(gs.mStoryModelUtilComponent)
ty.TextToolsComponent = typeof(gs.TextToolsComponent)
-- ty.AdaptSceneBGComponent = typeof(gs.AdaptSceneBGComponent)
-- ty.SceneBGComponent = typeof(gs.SceneBGComponent)

ty.MoveComponent = typeof(gs.MoveComponent)
ty.LifeCycleCompoment = typeof(gs.LifeCycleCompoment)
ty.SceneToUIComponent = typeof(gs.SceneToUIComponent)
ty.ColliderCall = typeof(gs.ColliderCall)
ty.PhysicsFrame = typeof(gs.PhysicsFrame)
ty.PhysicsCollision2D = typeof(gs.PhysicsCollision2D)
ty.PhysicsTrigger2D = typeof(gs.PhysicsTrigger2D)

ty.FadeModelComponent = typeof(gs.FadeModelComponent)
ty.UIDoTween = typeof(gs.UIDoTween)

--Other
ty.PostProcessing = typeof(gs.PostProcessing)
ty.CommandBufferBlur = typeof(gs.CommandBufferBlur)

ty.PlayMakerFSM = typeof(gs.PlayMakerFSM)
ty.DisplayUGUI = typeof(gs.DisplayUGUI)
ty.MediaPlayer = typeof(gs.MediaPlayer)

ty.FogRevealerUnit = typeof(gs.FogRevealerUnit)
ty.ScrollEffect = typeof(gs.ScrollEffect)
ty.ScrollEffectItem = typeof(gs.ScrollEffectItem)
ty.ArcScrollListView = typeof(gs.ArcScrollListView)
ty.ArcScrollItem = typeof(gs.ArcScrollItem)

ty.GraphicBlit = typeof(CS.GraphicBlit)
ty.FogOfWarManager = typeof(gs.FogOfWarManager)
ty.RaycastEmptyEvent = typeof(gs.RaycastEmptyEvent)

--Unity
ty.Transform = typeof(gs.Transform)
ty.RectTransform = typeof(gs.RectTransform)
ty.MeshRenderer = typeof(gs.MeshRenderer)
ty.MeshFilter = typeof(gs.MeshFilter)
ty.SkinnedMeshRenderer = typeof(gs.SkinnedMeshRenderer)
ty.CapsuleCollider = typeof(gs.CapsuleCollider)
ty.CapsuleCollider2D = typeof(gs.CapsuleCollider2D)

ty.Rigidbody = typeof(gs.Rigidbody)
ty.Rigidbody2D = typeof(gs.Rigidbody2D)

ty.Camera = typeof(gs.Camera)
ty.Canvas = typeof(gs.Canvas)
ty.Slider = typeof(gs.Slider)
ty.Button = typeof(gs.Button)
ty.Image = typeof(gs.Image)
ty.Text = typeof(gs.Text)
ty.InputField = typeof(gs.InputField)
ty.Renderer = typeof(gs.Renderer)
ty.ScrollRect = typeof(gs.ScrollRect)
ty.BoxCollider = typeof(gs.BoxCollider)
ty.BoxCollider2D = typeof(gs.BoxCollider2D)
ty.CircleCollider2D = typeof(gs.CircleCollider2D)
ty.Collider2D = typeof(gs.Collider2D)

ty.SphereCollider = typeof(gs.SphereCollider)
ty.MeshCollider = typeof(gs.MeshCollider)
ty.Collider = typeof(gs.Collider)

ty.CharacterController = typeof(gs.CharacterController)
ty.HorizontalLayoutGroup = typeof(gs.HorizontalLayoutGroup)
ty.VerticalLayoutGroup = typeof(gs.VerticalLayoutGroup)
ty.LayoutElement = typeof(gs.LayoutElement)
ty.LineRenderer = typeof(gs.LineRenderer)
ty.RenderTexture = typeof(gs.RenderTexture)
ty.RawImage = typeof(gs.RawImage)
ty.Animation = typeof(gs.Animation)
ty.ContentSizeFitter = typeof(gs.ContentSizeFitter)
ty.CanvasGroup = typeof(gs.CanvasGroup)
ty.Toggle = typeof(gs.Toggle)
ty.ToggleGroup = typeof(gs.ToggleGroup)
ty.Dropdown = typeof(gs.Dropdown)
ty.Outline = typeof(gs.Outline)
ty.Animator = typeof(gs.Animator)
ty.GridLayoutGroup = typeof(gs.GridLayoutGroup)
ty.GraphicRaycaster = typeof(gs.GraphicRaycaster)
ty.AudioSource = typeof(gs.AudioSource)
ty.SpriteRenderer = typeof(gs.SpriteRenderer)
ty.AudioListener = typeof(gs.AudioListener)
ty.PhysicsRaycaster = typeof(gs.PhysicsRaycaster)
ty.Shadow = typeof(gs.Shadow)
ty.AspectRatioFitter = typeof(gs.AspectRatioFitter)
ty.ParticleSystem = typeof(gs.ParticleSystem)
ty.NavMeshAgent = typeof(gs.NavMeshAgent)
ty.NavMeshObstacle = typeof(gs.NavMeshObstacle)
ty.VideoPlayer = typeof(gs.VideoPlayer)
ty.MediaPlayer = typeof(gs.MediaPlayer)
ty.TMP_Text = typeof(gs.TMP_Text)
ty.TMP_LinkInfo = typeof(gs.TMP_LinkInfo)
ty.TMP_TextUtilities = typeof(gs.TMP_TextUtilities)
ty.TextMeshProLink = typeof(gs.TextMeshProLink)

ty.PathManager = typeof(gs.PathManager)
ty.PathMoveComponent = typeof(gs.PathMoveComponent)

--eff
ty.WaterFallDissolveCtr = typeof(gs.WaterFallDissolveCtr)
ty.DissolveBaseCtr = typeof(gs.DissolveBaseCtr)

ty.UnityDebug = typeof(gs.Debug)

---Final IK
ty.FinalIKUtil = typeof(gs.FinalIKUtil)

ty.LookAtIK = typeof(gs.LookAtIK)
ty.BipedIK = typeof(gs.BipedIK)
ty.FullBodyBipedIK = typeof(gs.FullBodyBipedIK)
