-- from 093 boss演出配置表.xlsx

local boss_show_data=

{
	["6304"]={ leave_eff={"6304_leave.prefab"}, leave_eff_point={0}, enter_eff={"6304_enter.prefab"}, enter01_eff={}, standby_eff={"6304_standby.prefab"}, change_eff={"6304_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6304_appear.prefab", leave_sound="Boss/sfx_boss_6304_out.prefab", enter_sound="Boss/sfx_boss_6304_return.prefab", enter01_sound="", change_sound="Boss/sfx_boss_6304_energy.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6304_b"]={ leave_eff={"6304_leave.prefab"}, leave_eff_point={0}, enter_eff={"6304_enter.prefab"}, enter01_eff={}, standby_eff={"6304_standby.prefab"}, change_eff={"6304_change.prefab"}, change02_eff={}, standby_sound="", leave_sound="Boss/sfx_boss_6304_out.prefab", enter_sound="Boss/sfx_boss_6304_return.prefab", enter01_sound="", change_sound="Boss/sfx_boss_6304_energy.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6304_h"]={ leave_eff={"6304_h_leave.prefab"}, leave_eff_point={0}, enter_eff={"6304_h_enter.prefab"}, enter01_eff={}, standby_eff={"6304_h_standby.prefab"}, change_eff={"6304_h_change.prefab"}, change02_eff={}, standby_sound="", leave_sound="Boss/sfx_boss_6304_out.prefab", enter_sound="Boss/sfx_boss_6304_return.prefab", enter01_sound="", change_sound="Boss/sfx_boss_6304_energy.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6304_d"]={ leave_eff={"6304_leave.prefab"}, leave_eff_point={0}, enter_eff={"6304_enter.prefab"}, enter01_eff={}, standby_eff={"6304_standby.prefab"}, change_eff={"6304_change.prefab"}, change02_eff={}, standby_sound="", leave_sound="Boss/sfx_boss_6304_out.prefab", enter_sound="Boss/sfx_boss_6304_return.prefab", enter01_sound="", change_sound="Boss/sfx_boss_6304_energy.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6305"]={ leave_eff={"6305_leave.prefab","6305_leave_camera.prefab"}, leave_eff_point={4,0}, enter_eff={}, enter01_eff={}, standby_eff={"6305_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6305_appear.prefab", leave_sound="Boss/sfx_boss_6305_change01.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6306"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"6306_enter.prefab"}, enter01_eff={}, standby_eff={}, change_eff={}, change02_eff={}, standby_sound="", leave_sound="", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6307"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"6307_enter.prefab","6307_enter_camera.prefab","6307_enter_wq.prefab"}, enter01_eff={}, standby_eff={}, change_eff={}, change02_eff={}, standby_sound="", leave_sound="", enter_sound="Boss/sfx_boss_6307_change.prefab", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6309"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6309_standby.prefab"}, change_eff={"6309_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6309_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6309_out.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6107"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6107_standby.prefab","6107_standby_camera.prefab"}, change_eff={"6107_change.prefab"}, change02_eff={"6107_change02.prefab"}, standby_sound="Boss/sfx_boss_6107_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6107_change01.prefab", change02_sound="Boss/sfx_boss_6107_change02.prefab", standby_cv="", levea_cv="", enter_music=0
},
	["6310"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6310_standby.prefab"}, change_eff={"6310_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6310_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6310_out.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6311"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6311_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6311_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6303"]={ leave_eff={"6303_leave.prefab"}, leave_eff_point={0}, enter_eff={"6303_enter.prefab"}, enter01_eff={"6303_enter_01.prefab"}, standby_eff={"6303_standby.prefab"}, change_eff={"6303_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6303_appear.prefab", leave_sound="Boss/sfx_boss_6303_out.prefab", enter_sound="Boss/sfx_boss_6303_return.prefab", enter01_sound="Boss/sfx_boss_6303_return01.prefab", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6303_h"]={ leave_eff={"boss_yuansu/6303_h_leave.prefab"}, leave_eff_point={0}, enter_eff={"boss_yuansu/6303_h_enter.prefab"}, enter01_eff={"boss_yuansu/6303_h_enter_01.prefab"}, standby_eff={"boss_yuansu/6303_h_standby.prefab"}, change_eff={"boss_yuansu/6303_h_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6303_appear.prefab", leave_sound="Boss/sfx_boss_6303_out.prefab", enter_sound="Boss/sfx_boss_6303_return.prefab", enter01_sound="Boss/sfx_boss_6303_return01.prefab", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6302"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6302_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6302_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6302_b"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"boss_yuansu/6302_b_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6302_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6312"]={ leave_eff={}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6312_standby.prefab","6312_standby_camera.prefab"}, change_eff={"6312_change.prefab"}, change02_eff={"6312_change01.prefab"}, standby_sound="Boss/sfx_boss_6312_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6312_change01.prefab", change02_sound="Boss/sfx_boss_6312_change02.prefab", standby_cv="", levea_cv="", enter_music=0
},
	["6313"]={ leave_eff={"6313_change.prefab","6313_change_hand.prefab"}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6313_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6313_appear.prefab", leave_sound="Boss/sfx_boss_6313_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6313_2"]={ leave_eff={"6313_change.prefab","6313_change_hand.prefab"}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"6313_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6313_appear.prefab", leave_sound="Boss/sfx_boss_6313_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6313_h"]={ leave_eff={"boss_yuansu/6313_h_change.prefab","boss_yuansu/6313_h_change_hand.prefab"}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"boss_yuansu/6313_h_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6313_appear.prefab", leave_sound="Boss/sfx_boss_6313_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6313_h_2"]={ leave_eff={"boss_yuansu/6313_h_change.prefab","boss_yuansu/6313_h_change_hand.prefab"}, leave_eff_point={0}, enter_eff={}, enter01_eff={}, standby_eff={"boss_yuansu/6313_h_standby.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6313_appear.prefab", leave_sound="Boss/sfx_boss_6313_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6314"]={ leave_eff={}, leave_eff_point={}, enter_eff={}, enter01_eff={}, standby_eff={"6314_standby.prefab"}, change_eff={"6314_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6314_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6314_change.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6315"]={ leave_eff={}, leave_eff_point={}, enter_eff={}, enter01_eff={}, standby_eff={"6314_standby.prefab"}, change_eff={"6314_change.prefab"}, change02_eff={}, standby_sound="Boss/sfx_boss_6314_appear.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="Boss/sfx_boss_6314_change.prefab", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6316_b"]={ leave_eff={"6316_b_leave_changjing.prefab","6316_b_leave.prefab"}, leave_eff_point={4,0}, enter_eff={}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="mon_6316_b_cv_01.prefab", levea_cv="mon_6316_b_cv_04.prefab", enter_music=0
},
	["6316_b_2"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"6316_b_2_enter_changjing.prefab","6316_b_2_enter_Bone237_l.prefab","6316_b_2_enter_Bone237_r.prefab","6316_b_2_enter_Bone245_l.prefab","6316_b_2_enter_Bone245_r.prefab","6316_b_2_enter_Bone251_l.prefab","6316_b_2_enter_Bone251_r.prefab","6316_b_2_enter_Bone260_l.prefab","6316_b_2_enter_Bone260_r.prefab"}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=65
},
	["6316_g"]={ leave_eff={"6316_b_leave_changjing.prefab","6316_b_leave.prefab"}, leave_eff_point={4,0}, enter_eff={}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="mon_6316_b_cv_01.prefab", levea_cv="mon_6316_b_cv_04.prefab", enter_music=0
},
	["6316_g_2"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"6316_b_2_enter_changjing.prefab","6316_b_2_enter_Bone237_l.prefab","6316_b_2_enter_Bone237_r.prefab","6316_b_2_enter_Bone245_l.prefab","6316_b_2_enter_Bone245_r.prefab","6316_b_2_enter_Bone251_l.prefab","6316_b_2_enter_Bone251_r.prefab","6316_b_2_enter_Bone260_l.prefab","6316_b_2_enter_Bone260_r.prefab"}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=65
},
	["6316_h"]={ leave_eff={"6316_b_leave_changjing.prefab","6316_b_leave.prefab"}, leave_eff_point={4,0}, enter_eff={}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="mon_6316_b_cv_01.prefab", levea_cv="mon_6316_b_cv_04.prefab", enter_music=0
},
	["6316_h_2"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"6316_b_2_enter_changjing.prefab","6316_b_2_enter_Bone237_l.prefab","6316_b_2_enter_Bone237_r.prefab","6316_b_2_enter_Bone245_l.prefab","6316_b_2_enter_Bone245_r.prefab","6316_b_2_enter_Bone251_l.prefab","6316_b_2_enter_Bone251_r.prefab","6316_b_2_enter_Bone260_l.prefab","6316_b_2_enter_Bone260_r.prefab"}, enter01_eff={}, standby_eff={"6316_b_standby.prefab","6316_b_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_b_appear.prefab", leave_sound="Boss/sfx_boss_6316_b_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=65
},
	["6316_d"]={ leave_eff={"boss_yuansu/6316_d_leave_changjing.prefab","boss_yuansu/6316_d_leave.prefab"}, leave_eff_point={4,0}, enter_eff={}, enter01_eff={}, standby_eff={"boss_yuansu/6316_d_standby.prefab","boss_yuansu/6316_d_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_d_appear.prefab", leave_sound="Boss/sfx_boss_6316_d_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="mon_6316_b_cv_01.prefab", levea_cv="mon_6316_b_cv_04.prefab", enter_music=0
},
	["6316_d_2"]={ leave_eff={}, leave_eff_point={0}, enter_eff={"boss_yuansu/6316_d_2_enter_changjing.prefab","boss_yuansu/6316_d_2_enter_Bone237_l.prefab","boss_yuansu/6316_d_2_enter_Bone237_r.prefab","boss_yuansu/6316_d_2_enter_Bone245_l.prefab","boss_yuansu/6316_d_2_enter_Bone245_r.prefab","boss_yuansu/6316_d_2_enter_Bone251_l.prefab","boss_yuansu/6316_d_2_enter_Bone251_r.prefab","boss_yuansu/6316_d_2_enter_Bone260_l.prefab","boss_yuansu/6316_d_2_enter_Bone260_r.prefab"}, enter01_eff={}, standby_eff={"boss_yuansu/6316_d_standby.prefab","boss_yuansu/6316_d_standby_eye.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6316_d_appear.prefab", leave_sound="Boss/sfx_boss_6316_d_change.prefab", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=65
},
	["6317"]={ leave_eff={}, leave_eff_point={}, enter_eff={}, enter01_eff={}, standby_eff={"6317_standby.prefab","6317_standby_Camera.prefab","6317_standby_changjing.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6317_standby.prefab", leave_sound="", enter_sound="", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=0
},
	["6317_2"]={ leave_eff={}, leave_eff_point={}, enter_eff={"6317_2_enter.prefab"}, enter01_eff={}, standby_eff={"6317_standby.prefab","6317_standby_Camera.prefab","6317_standby_changjing.prefab"}, change_eff={}, change02_eff={}, standby_sound="Boss/sfx_boss_6317_standby.prefab", leave_sound="", enter_sound="Boss/sfx_boss_6317_change.prefab", enter01_sound="", change_sound="", change02_sound="", standby_cv="", levea_cv="", enter_music=87
}
}

return boss_show_data