-- from 151 新手引导配置表.xlsx

local guide_data=

{
	[1001]={ line_id=1, happen_type=1, happen_arg={10011}, dup={2,1001}, can_pass=0, is_pause=0, is_strike=1, award_type={}, award={}, guide_group={}
},
	[1002]={ line_id=1, happen_type=25, happen_arg={2,1001}, dup={}, can_pass=0, is_pause=0, is_strike=1, award_type={}, award={}, guide_group={}
},
	[1011]={ line_id=1, happen_type=19, happen_arg={2,1001}, dup={}, can_pass=0, is_pause=0, is_strike=1, award_type={}, award={}, guide_group={}
},
	[1013]={ line_id=1, happen_type=20, happen_arg={2,1001,1110,1110,8}, dup={}, can_pass=0, is_pause=1, is_strike=1, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="After the Operator starts the battle, an <color=#1792ff>Action Countdown Timer</color> will appear. \nYou can attack before the timer ends.", posx=-200, posy=123, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={5,472,48,0,0}, is_camera=0, display_control="", control="GuideFrame3", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Releasing skills consumes <color=#1792ff>Energy</color>. \nHere shows the <color=#1792ff>Energy</color> the Operator has. Each Operator has an individual Energy slot.", posx=-78, posy=179, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="GuideFrame4", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Here shows the <color=#1792ff>Energy</color> required to use a skill.", posx=-70, posy=123, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_soulBG", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Use <color=#1792ff>Energy</color> now and activate Alicia's skill - <color=#1792ff>Shimmering·Moonblade</color>!!", posx=-208, posy=123, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_SkillItem1", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=1, text_box=2, click_efx_name="" },
}
},
	[1014]={ line_id=1, happen_type=12, happen_arg={2,1001,3003}, dup={}, can_pass=0, is_pause=1, is_strike=1, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="This is the <color=#1792ff>action bar</color> for characters. The action order of all characters on the battlefield is displayed here. It's now the enemy's turn.", posx=-213, posy=179, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="GuideFrame1", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[1015]={ line_id=1, happen_type=21, happen_arg={2,2,1001,1110,1110,8}, dup={}, can_pass=0, is_pause=1, is_strike=1, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Now release Alicia's skill again - <color=#1792ff>Shimmering·Moonblade</color>!!", posx=-319, posy=123, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_SkillItem1", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=1, text_box=1, click_efx_name="" },
}
},
	[1016]={ line_id=1, happen_type=27, happen_arg={2,2,1001,1110,111001,8}, dup={}, can_pass=0, is_pause=1, is_strike=1, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Now use Alicia's <color=#1792ff>Energy Burst</color>—<color=#1792ff>Radiant·Judgment</color>.", posx=-215, posy=181, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_SkillMaxItem", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=1, text_box=2, click_efx_name="" },
}
},
	[1017]={ line_id=2, happen_type=4, happen_arg={2,1001}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Tap here to view the stage information.", posx=-11, posy=113, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_1_1002", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Tap here to prepare for battle.", posx=-4, posy=136, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_challenge", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Tap the <color=#1792ff>glowing area of formation </color> to deploy the Operator.", posx=-4, posy=149, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="tofight_formation_tile_1_2", control="tofight_formation_tile_texture_1_2", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="fx_ui_common_guide_3" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to select and deploy the Operator.", posx=-389, posy=133, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=1, display_control="", control="tofight_formation_2_1002_select_head_1305", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="fx_ui_common_guide_3" },
		[5]={ next_id=6, uicode=0, place={}, msg="Tap the corresponding Operator avatar on the left for quick cultivation.", posx=450, posy=158, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_formation_item_1305", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Tap the upgrade button to enter the Operator's cultivation interface.", posx=-60, posy=167, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_HeroLvlUp_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Use the relevant <color=#1792ff>Battle Report</color> to upgrade the Operator.", posx=-9, posy=167, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_HeroLvlUp_3", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[8]={ next_id=9, uicode=0, place={}, msg="Tap the auto-select button to automatically add Battle Reports.", posx=-110, posy=116, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_HeroLvlUp_4", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[9]={ next_id=10, uicode=0, place={}, msg="Then tap the upgrade button to upgrade Operator.", posx=-141, posy=147, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_HeroLvlUp_2", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[10]={ next_id=11, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={2}, is_camera=0, display_control="", control="guide_HeroLvlUpShowPanel_CloseBtn", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=0, click_efx_name="" },
		[11]={ next_id=12, uicode=0, place={}, msg="Tap here to return to the battle.", posx=200, posy=-147, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnClose_HeroDevelopPanel", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[12]={ next_id=0, uicode=0, place={}, msg="Operator deployed! Linker, start the battle now!", posx=-415, posy=137, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_formation_btnControl", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[1018]={ line_id=3, happen_type=20, happen_arg={2,1002,1305,1305,8}, dup={}, can_pass=0, is_pause=1, is_strike=1, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Here shows the enemy's <color=#1792ff>elemental weakness</color>. \nAttacks using the corresponding element will deal more damage.", posx=-100, posy=123, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeadArea_MonsterWeak", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="<size=18>Above HP displays the enemy's <color=#1792ff>stagger</color>.\n It redeces when enemy is attacked with its elemental weakness.\nWhen the stagger bar empties, the monster enters <color=#1792ff>Break state</color>.</size>", posx=-80, posy=123, areaw=800, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeadArea_MonsterHp", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=0, uicode=0, place={}, msg="This attack can empty the enemy's <color=#1792ff>stagger</color>.", posx=1, posy=135, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_SkillItem1", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=1, text_box=2, click_efx_name="" },
}
},
	[1021]={ line_id=5, happen_type=4, happen_arg={2,1003}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, the <color=#1792ff>Link Search System</color> opened. You can find new team members now!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Enter the Link Search interface from here.", posx=30, posy=118, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnRecruit", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Tap to enter the Regular Link interface.", posx=110, posy=108, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_recruit_tabItem_2", special_control={}, is_click=0, delay=750, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Tap here to use a <color=#1792ff>Link Permit</color> for Operator linking.", posx=-30, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="recruit_top_btn_one", special_control={}, is_click=0, delay=750, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[1030]={ line_id=6, happen_type=4, happen_arg={2,1002}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Tap here to view stage information.", posx=-11, posy=113, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_1_1003", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Tap here to enter pre-battle mode.", posx=-4, posy=136, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_challenge", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Deploying Operators with the same element activates corresponding buffs. You can check currently active effects here.", posx=-344, posy=92, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_Element", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Linker, start the battle now!", posx=-65, posy=137, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_formation_btnControl", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="fx_ui_common_guide_3" },
}
},
	[1033]={ line_id=8, happen_type=26, happen_arg={"formation.FormationPanel",2,1004}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Tap on an unlocked grid to replace an Operator.", posx=-4, posy=149, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="tofight_formation_tile_3_2", control="tofight_formation_tile_texture_3_2", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="fx_ui_common_guide_3" },
}
},
	[1022]={ line_id=9, happen_type=14, happen_arg={2,1005}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="You can view enemy information for the stage from here.", posx=-265, posy=130, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_BtnEnemyInfo", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Enemies' elemental weakness is shown on the bottom right, and damage types on the left.", posx=452, posy=193, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeroDevelopNode", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Tap here to return to the battle interface.", posx=200, posy=-147, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_MonsterBtnClose", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="All stages have recommended lineups. From here, you can check the recommended levels and\nelements for the stage, tap to view detailed Elemental Weakness and Break effects.", posx=11, posy=-126, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_RecommandLv", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[1024]={ line_id=11, happen_type=14, happen_arg={2,1008}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="You can view an overview of environmental effects here.", posx=-208, posy=-114, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_BtnPosEff", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[1026]={ line_id=13, happen_type=2, happen_arg={2,1003}, dup={}, can_pass=0, is_pause=1, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Linker, <color=#1792ff>auto-battle</color> is on. Tap here to enable auto-battle!", posx=-300, posy=-131, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="AutoBtn1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[1027]={ line_id=14, happen_type=14, happen_arg={2,1102}, dup={}, can_pass=2, is_pause=0, is_strike=2, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="A new formation has been unlocked. Tap here to switch to another formation.", posx=46, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_BtnFormation", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=0, uicode=0, place={}, msg="Now choose the right formation based on the battlefield environment.", posx=384, posy=0, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_formation_ScrollerSelect", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[1028]={ line_id=15, happen_type=4, happen_arg={2,1109}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, <color=#1792ff>Base System</color> is now open, you can start building your home!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Enter Base from here.", posx=67, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem32", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Power Module provides Electric Power, and building construction and upgrades will use Electric Power. \nWithout enough Electric Power, you can't build or upgrade other buildings.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_nobuild_point_1", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap here to enter build mode.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_editor", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="<color=#1792ff>Titanium Materials</color> are produced by the Purification Workshop, Tap here to construct it.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_build_point_2", special_control={}, is_click=0, delay=1500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Purification Workshop is mainly used to produce <color=#1792ff>Titanium Materials</color>.", posx=-450, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_tips", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Tap to consume <color=#1792ff>Titanium Materials</color> to start building.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_btnCreate", special_control={}, is_click=0, delay=500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[8]={ next_id=9, uicode=0, place={}, msg="Training Module can produce a large amount of <color=#1792ff>Operation EXP Report</color> used to level up Operators. \nTap here to construct it.", posx=-100, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_build_point_3", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[9]={ next_id=10, uicode=0, place={}, msg="Production speeds up when Operators with relevant Base skills are stationed in the Training Module.", posx=-350, posy=224, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_tips", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[10]={ next_id=11, uicode=0, place={}, msg="Tap to consume <color=#1792ff>Titanium Materials</color> to start building.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_btnCreate", special_control={}, is_click=0, delay=500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[11]={ next_id=12, uicode=0, place={}, msg="Tap on the buildable area to construct a Dorm.", posx=3, posy=-180, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_build_point_5", special_control={}, is_click=0, delay=1500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[12]={ next_id=13, uicode=0, place={}, msg="The Dorm allows Operators to stay and recover fatigue. You can also DIY furniture arrangements to increase dorm comfort. Higher comfort speeds up Operators' fatigue recovery.", posx=-450, posy=203, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_tips", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[13]={ next_id=14, uicode=0, place={}, msg="Tap to consume <color=#1792ff>Titanium Materials </color> to start building.", posx=-200, posy=224, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseCreate_btnCreate", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[14]={ next_id=15, uicode=0, place={}, msg="Tap here to exit build mode.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_editor", special_control={}, is_click=0, delay=500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[15]={ next_id=16, uicode=0, place={}, msg="Tap the Purification Workshop again to enter it.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_nobuild_point_2", special_control={}, is_click=0, delay=1500, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[16]={ next_id=17, uicode=0, place={}, msg="Here you can check production status. Stationing Operators can speed up production of <color=#1792ff>Titanium Materials</color>.", posx=446, posy=-244, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_Produce", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[17]={ next_id=18, uicode=0, place={}, msg="Tap here to open the station info pop-up.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_ShowOccupants", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[18]={ next_id=19, uicode=0, place={}, msg="Tap here to station an Operator.", posx=-66, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_btnSettled", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[19]={ next_id=20, uicode=0, place={}, msg="Tap to select an Operator.", posx=3, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="hero_list_first_item_1", special_control={}, is_click=0, delay=450, next_need_id=1110, is_wait_sever=0, text_box=2, click_efx_name="" },
		[20]={ next_id=21, uicode=0, place={}, msg="Here you can view an Operator's Base skills. Different Operators have different\nBase skills. Reaching certain development stages can unlock a second Base skill.", posx=263, posy=280, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_settledTips", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[21]={ next_id=22, uicode=0, place={}, msg="Operators' initial fatigue value is 200. Fatigue reduces while working, and when it\nreaches 0, they will enter a fatigued state, negating the Base skills.", posx=150, posy=-124, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBaseSettleIn_tips", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[22]={ next_id=23, uicode=0, place={}, msg="Tap to confirm stationing the Operator.", posx=-66, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_BtnCommit", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[23]={ next_id=24, uicode=0, place={}, msg="Tap here to consume production robots and speed up production.", posx=118, posy=-124, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BuildBase_BtnSpUp", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[24]={ next_id=25, uicode=0, place={}, msg="Tap here to add all current production robots.", posx=-66, posy=124, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_buildbase_UAVUse_BtnRR", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[25]={ next_id=26, uicode=0, place={}, msg="Tap confirm to consume the corresponding number of robots to accelerate production for more items.", posx=-130, posy=124, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_buildbase_UAVUse_BtnSure", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[26]={ next_id=27, uicode=0, place={}, msg="Tap here to return to Base.", posx=200, posy=-147, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnClose_BuildBaseRoomUI", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[27]={ next_id=28, uicode=0, place={}, msg="Tap here to claim all rewards.", posx=-66, posy=124, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_buildBase_6", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[28]={ next_id=29, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={2}, is_camera=0, display_control="", control="guide_ShowAwardPanel_CloseBtn", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[29]={ next_id=30, uicode=0, place={}, msg="Tap again to enter the Dorm and arrange for Operator station.", posx=164, posy=-180, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_nobuild_point_5", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[30]={ next_id=0, uicode=0, place={}, msg="Tap here to furnish the dorm and increase dorm comfort.", posx=-266, posy=156, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_Dormitory_Edit", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[1031]={ line_id=17, happen_type=28, happen_arg={2,1003}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={}
},
	[1041]={ line_id=18, happen_type=4, happen_arg={2,1007}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="The number of Elite monsters has increased in this satge. Danger level elevated. Strengthen your Operators before proceeding.", posx=-11, posy=113, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_1_1008", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[2002]={ line_id=20, happen_type=4, happen_arg={2,1104}, dup={}, can_pass=2, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, Promotion Train is now open! Hurry up and check it out.", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=-383, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem1", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter Resources from here.", posx=0, posy=108, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainPlay_4", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to enter Promotion Train.", posx=-332, posy=260, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="MainPlayDupItem_2", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[5]={ next_id=0, uicode=0, place={}, msg="Operators with different elements need specific materials for Promotion Train.", posx=480, posy=213, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_dupPotency_tips", special_control={}, is_click=1, delay=700, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[2003]={ line_id=21, happen_type=4, happen_arg={2,1102}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you've obtained a <color=#1792ff>Model</color> from the battle. Load it onto your Operator now!", posx=250, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem5", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="hero_list_first_item", special_control={}, is_click=0, delay=550, next_need_id=1110, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to enter Operator Sigil system.", posx=101, posy=108, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeroDevelop_Btn_HandRing", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Tap here to load a Sigil.", posx=-5, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeroBracelets_Btn_Equip", special_control={}, is_click=0, delay=700, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Tap Enhance to enter the current Sigil cultivation interface.", posx=-192, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeroBracelets_Btn_Strengthen", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Tap to add Enhance materials.", posx=-5, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BraceletStrengthen_Btn_1", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[8]={ next_id=9, uicode=0, place={}, msg="Select one Sigil Enhancer.", posx=-5, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_BraceletMaterialPanel_Btn_8101", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[9]={ next_id=10, uicode=0, place={}, msg="Tap Enhance to consume selected materials and upgrade the Sigil level.", posx=-307, posy=125, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BraceletStrengthen_Btn_Strengthen", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[10]={ next_id=11, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={2}, is_camera=0, display_control="", control="guide_BraceletStrengthenSucPanel_CloseBtn", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=0, click_efx_name="" },
		[11]={ next_id=12, uicode=0, place={}, msg="<color=#1792ff>Regular Sigil System</color> is now open. You can obtain new Sigils here!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[12]={ next_id=13, uicode=0, place={}, msg="Enter Link Search from here.", posx=0, posy=118, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnRecruit", special_control={}, is_click=0, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[13]={ next_id=0, uicode=0, place={}, msg="You can obtain more and rarer Sigils from Regular Sigil.", posx=234, posy=108, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_recruit_tabItem_3", special_control={}, is_click=0, delay=750, next_need_id=4, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[2005]={ line_id=23, happen_type=4, happen_arg={2,1010}, dup={}, can_pass=2, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, the Missions hall is now open!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnMainUI", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter the Missions hall from here.", posx=-4, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_main_ui_3", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Here shows the cumulative score of Missions.\n You can claim rewards when the score reaches different stages each day.", posx=-54, posy=174, areaw=500, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_dailyTask_2", special_control={}, is_click=1, delay=700, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=0, uicode=0, place={}, msg="Linker, tap now to claim your completed Missions rewards!", posx=-371, posy=98, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_mGuideDaily_1", special_control={}, is_click=0, delay=700, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[2006]={ line_id=24, happen_type=4, happen_arg={2,1111}, dup={}, can_pass=2, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you have access to Subconscious Deepseek. Please proceed to explore.", posx=220, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter the unknown Challenge from here.", posx=15, posy=114, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainPlay_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to enter Subconscious Deepseek.", posx=-5, posy=288, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChallengeEnterItem_3", special_control={}, is_click=0, delay=550, next_need_id=3, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Select the first area.", posx=-35, posy=-161, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DomainSurveyItem_1", special_control={}, is_click=0, delay=2000, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Select the first development area.", posx=-4, posy=146, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DomainSurveyStageItem_2001", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=0, uicode=0, place={}, msg="Start brain development now!", posx=-3, posy=119, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="survey_tofight_challenge", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[2007]={ line_id=25, happen_type=4, happen_arg={2,1114}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you have access to Maze Exploration. Please proceed to explore.", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter the unknown Challenge from here.", posx=15, posy=145, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainPlay_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to enter Maze Exploration.", posx=-5, posy=294, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChallengeEnterItem_19", special_control={}, is_click=0, delay=550, next_need_id=19, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Choose the first area to enter.", posx=-4, posy=332, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_maze_mazeItem_1", special_control={}, is_click=0, delay=650, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="The maze is full of dangers and treasures. If you can't proceed further,\n you can reset the stage by tapping the reset button", posx=46, posy=-115, areaw=500, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_mazeScene_1", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Here shows the progress of chests opened in the current maze (resetting won't reset the chests)", posx=-478, posy=57, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_mazeScene_4", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[8]={ next_id=0, uicode=0, place={}, msg="If you can't find yourself, tap here to quickly locate yourself at the center of the screen", posx=-428, posy=93, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_mazeScene_5", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[3001]={ line_id=26, happen_type=4, happen_arg={2,1207}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you've obtained a <color=#1792ff>Model</color> from the battle. Load it onto your Operator now!", posx=260, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=-388, posy=163, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem5", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="hero_list_first_item", special_control={}, is_click=0, delay=550, next_need_id=1110, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap here to enter the Model system interface.", posx=151, posy=109, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_HeroDevelop_Btn_Equip", special_control={}, is_click=0, delay=700, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Tap here to start loading the Model.", posx=0, posy=140, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="Equip_Load_2", special_control={}, is_click=0, delay=2600, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Tap to view Model information.", posx=2, posy=146, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=1, display_control="", control="funcTips_guide_HeroEquipMaterial_equip_5001", special_control={}, is_click=0, delay=650, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Tap here to load the Model for your Operator.", posx=-30, posy=115, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=1, display_control="", control="funcTips_guide_HeroEquipMaterial_btn_off", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[8]={ next_id=9, uicode=0, place={}, msg="Choose the second Model load slot.", posx=2, posy=157, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="Equip_Load_5", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[9]={ next_id=10, uicode=0, place={}, msg="Tap to view Model information.", posx=0, posy=140, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=1, display_control="", control="funcTips_guide_HeroEquipMaterial_equip_5002", special_control={}, is_click=0, delay=650, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[10]={ next_id=0, uicode=0, place={}, msg="Tap here to load the Model for your Operator.\n If same type of Models are loaded, the set effects will automatically activate.", posx=150, posy=150, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=1, display_control="", control="funcTips_guide_HeroEquipMaterial_btn_off", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[3002]={ line_id=27, happen_type=4, happen_arg={2,1215}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, the special Story Battle is now open! Go check it out.", posx=130, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnClose", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Enter the special Story chapter from here.", posx=-67, posy=-93, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnDifficulty", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Choose the corresponding chapter to enter.", posx=-6, posy=256, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainStageStart", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Start the first Challenge!", posx=-7, posy=117, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="tofight_1_6001", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[4001]={ line_id=28, happen_type=4, happen_arg={2,1310}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you now have access to Sub-Story. Please proceed to explore.", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="", posx=-52, posy=145, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainPlay_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap to enter Sub-Story.", posx=-8, posy=288, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChallengeEnterItem_27", special_control={}, is_click=0, delay=550, next_need_id=27, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Here shows the current gameplay level. \nYou can Tap to claim rewards after leveling up.", posx=280, posy=-109, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_CycleMainPanel_btn_1", special_control={}, is_click=1, delay=1600, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Tap here to view current tasks for this gameplay, tasks refresh every 15 days.", posx=298, posy=-114, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_CycleMainPanel_btn_2", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=8, uicode=0, place={}, msg="Tap here to access the talent system for this gameplay, increase gameplay level to earn talent points.", posx=-479, posy=99, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_CycleMainPanel_btn_3", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[8]={ next_id=0, uicode=0, place={}, msg="You can start the challenge from here.", posx=-30, posy=142, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_CycleMainPanel_btn_4", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[6001]={ line_id=30, happen_type=2, happen_arg={2,1111}, dup={}, can_pass=0, is_pause=1, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Linker, <color=#1792ff>3x Battle Speed</color> is now activated! Tap here to accelerate the battle!", posx=-350, posy=-131, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_fight_speedBtn", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[7001]={ line_id=31, happen_type=4, happen_arg={2,1304}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, <color=#1792ff>Union System</color> is now open! Time to build your own homeland!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=0, msg_type=0, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem17", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=0, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter the Union from here. Joining a Union allows you to fight alongside other Linkers\nand earn more rewards.", posx=-250, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_mainUIBtn_Guild", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="You can view and choose to join other Unions from here.", posx=150, posy=118, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_GuildJoinTabItem_1", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=0, uicode=0, place={}, msg="You can create your own Union from here.", posx=120, posy=148, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_GuildJoinTabItem_2", special_control={}, is_click=1, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[8001]={ line_id=32, happen_type=4, happen_arg={2,1315}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, you have gained access to City Unlimited. Please proceed to explore.", posx=270, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="", posx=0, posy=0, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Enter the unknown Challenge from here.", posx=15, posy=145, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_BtnMainPlay_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Tap to enter City Unlimited.", posx=-5, posy=294, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChallengeEnterItem_40", special_control={}, is_click=0, delay=550, next_need_id=40, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[9001]={ line_id=33, happen_type=4, happen_arg={2,1211}, dup={}, can_pass=0, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Linker, <color=#1792ff>Arena</color> is now available! Participate to earn generous rewards!", posx=214, posy=-122, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_View_CloseAlll", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=0, uicode=0, place={}, msg="", posx=67, posy=158, areaw=300, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_guide_NavigationLink_BtnItem201", special_control={}, is_click=0, delay=450, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[10001]={ line_id=101, happen_type=15, happen_arg={"cycle.CycleTalentPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="You can view your current Talent Points here. \nIncrease the Battle Record to earn talent points.", posx=-160, posy=-122, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_Talent_TalentPoint", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Tap to view the effects of talents and the talent points needed to activate them.", posx=0, posy=-160, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_Talent_item_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=0, uicode=0, place={}, msg="You can view an overview of all activated talents from here.", posx=230, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_Talent_Progress", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[10002]={ line_id=102, happen_type=15, happen_arg={"cycle.CycleBuffSelectPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="The first stage of exploration requires choosing the right campaign strategy.", posx=500, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_CycleBuffItem_1", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[10003]={ line_id=103, happen_type=15, happen_arg={"cycle.CycleComboPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=0, uicode=0, place={}, msg="Operators in exploration need to be recruited from existing Operators. Quickly choose a suitable recruitment team!", posx=500, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="CycleComboItem_1", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[10004]={ line_id=104, happen_type=15, happen_arg={"cycle.CycleRecruitPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Operators of different rarities require different amounts of <color=#1792ff>Logistics Points</color>. \nCheck your remaining points here.", posx=-300, posy=-122, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_CycleTopPanel_HopeItem", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=0, uicode=0, place={}, msg="Tap to enter the recruitment interface for the respective attribute's Operators.", posx=450, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_CycleRecruitItem_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[10005]={ line_id=105, happen_type=15, happen_arg={"dup.DupChipInfoView",10602}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Tap here to enter the set drop selection interface of Model instance.", posx=311, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChipInfo_BtnSuit", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Here shows different set types of Models. Tap to view the set attributes of the respective Model.", posx=391, posy=340, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChipSelect_Suit", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=0, uicode=0, place={}, msg="Here shows the attributes of the currently selected Model set. Switching to other Models can change the drop type in advanced and core Model levels.", posx=-450, posy=250, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupChipSelect_Info", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
}
},
	[10006]={ line_id=106, happen_type=15, happen_arg={"dup.DupCodeHopeMainPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Here shows different difficulty chapters.\n Only by completing the current difficulty can you Challenge the next one.", posx=550, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_DupCodeHopeMainPanel_Tab", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Tap here to enter the selected chapter's stage interface.", posx=-150, posy=280, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_dupCode_levelItem_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Here shows the exploration rate of the current chapter.\n Reach an exploration rate of 100% to claim clear rewards.", posx=-415, posy=-100, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_codeHope_explore", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Tap a stage to open the stage information interface.", posx=262, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_codeHope_dupItem_1001", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Here shows the current stage's deployment restrictions. Each Operator has 5 Stamina points, and passing a stage will deduct the corresponding\nStamina. When Operators' Stamina reaches 0, they can no longer be deployed.", posx=-430, posy=150, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_codeHope_Tips1", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=1, click_efx_name="" },
		[6]={ next_id=0, uicode=0, place={}, msg="Let's start exploring the Challenge!", posx=-70, posy=100, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="funcTips_codeHope_Fight", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[10007]={ line_id=107, happen_type=15, happen_arg={"guild.GuildBossMainUI",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Here shows the activity's start or end times.\n Tap on the current ranking to view corresponding ranking reward information.", posx=320, posy=-144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_guildeBoss_tips_1", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Here shows the current Boss round. \nOnce you finish a Boss round, a new Challenge round begins, and monster attributes will increase.", posx=-290, posy=-144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_guildeBoss_tips_2", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Here shows remaining Daily Challenge attempts.\n Resets at 5:00 (UTC-5) daily when depleted.", posx=-190, posy=-144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_guildeBoss_tips_3", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Tap here to view the battle records of Linkers in the Union during this event.", posx=-285, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_guildeBoss_tips_4", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[10008]={ line_id=108, happen_type=15, happen_arg={"doundless.DoundlessPanel",0}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="Here shows the current zone and district, and the reset time for the next allocation.", posx=300, posy=-144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="functips_doundless_leftTop", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Here shows the current zone's buff effects, disturbance index, and ranking points.", posx=-280, posy=-160, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="functips_doundless_skill", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Here you can Tap to view reward and ranking information.", posx=350, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="functips_doundless_leftBottom", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=5, uicode=0, place={}, msg="Let's start exploring the Challenge!", posx=-100, posy=200, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_Doundless_DupItem_1", special_control={}, is_click=0, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[5]={ next_id=6, uicode=0, place={}, msg="Here displays the maximum score attainable for the current stage.", posx=-150, posy=-144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="functips_doundless_stageTitle", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[6]={ next_id=7, uicode=0, place={}, msg="Here shows the Challenge objectives for the current stage.", posx=-170, posy=155, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="mFunctips_doundless_stageTarget", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[7]={ next_id=0, uicode=0, place={}, msg="", posx=-140, posy=144, areaw=350, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="mFunctips_doundless_stageScore", special_control={}, is_click=1, delay=550, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[20001]={ line_id=202, happen_type=14, happen_arg={44,2204}, dup={}, can_pass=1, is_pause=0, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="A Sky Pillar Light has appeared on the battlefield. In its dim state, Concealment targets cannot be primary targets.\nIn its blazing state, Concealment is ineffective.", posx=-4, posy=249, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={5,225,230,0,55}, is_camera=0, display_control="tofight_formation_tile_2_2", control="tofight_formation_tile_texture_2_2", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=0, uicode=0, place={}, msg="Sky Pillar Light starts in a dim state, and Operators within its cross-shaped range\nwill replenish 1 Energy charge when releasing skills (up to 3). When Energy is full, it switches to a blazing state for 2 turns.", posx=-4, posy=249, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={5,225,230,0,55}, is_camera=0, display_control="tofight_formation_tile_2_2", control="tofight_formation_tile_texture_2_2", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
},
	[30001]={ line_id=301, happen_type=30, happen_arg={10001}, dup={}, can_pass=0, is_pause=1, is_strike=0, award_type={}, award={}, guide_group={
		[1]={ next_id=2, uicode=0, place={}, msg="We need to clear obstacles above the street <color=#1792ff>Pathway</color>.", posx=-4, posy=290, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_FieldExploration_prop_2", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[2]={ next_id=3, uicode=0, place={}, msg="Once close to an obstacle, tap the <color=#1792ff>Grab</color> skill to drag back and forth. Tap again to cancel grab.", posx=-4, posy=249, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_FieldExploration_prop_1", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[3]={ next_id=4, uicode=0, place={}, msg="Tap to release this skill and dash forward.\nWhen used near obstacles, you'll phase through them.", posx=-270, posy=149, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_FieldExploration_Skill_1003", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
		[4]={ next_id=0, uicode=0, place={}, msg="Obstacles can only move vertically or horizontally (depending on grab direction).", posx=-230, posy=149, areaw=400, msg_type=2, talker="", painting_up="", exit={0}, shade=1, move_next=1, box_type={1}, is_camera=0, display_control="", control="guide_FieldExploration_Skill_1004", special_control={}, is_click=1, delay=300, next_need_id=0, is_wait_sever=0, text_box=2, click_efx_name="" },
}
}
}

return guide_data