-- from 087 怪物档案配置表.xlsx

local manual_mon_data=

{
	[1]={ model="6104", name="Clawed Clerk", english="Kalan Lisa", story="Mutants commonly found around fortress cities—The remnants of business suits, neckties, and leather shoes still visible on their twisted forms tell their tragic origin—these were once white-collar workers toiling in cubicles. Perhaps moments before contamination, they had just closed a deal, finalized a proposal, received a promotion... or were rushing home to loved ones... Until the unknown catastrophe struck, ending everything in an instant.", hero_type=1, shadow="mon_archives_normal_6104.png", shadow_unlock="mon_archives_shadow_6104.png", dangerous=1, skill_list={298380,300086,3001}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[2]={ model="6109", name="Hammer Man", english="DAVIST", story="Originally workers from the mining facilities, these individuals underwent grotesque transformation after exposure to the Void Expanse during the Anchor Panic. Their mutated epidermal growths and aberrant biological structures indicate Stage III infection. Though clumsy in movement, they retain terrifying proficiency with mining hammers—a grim reminder of their former profession. Unprepared travelers are strongly advised to disengage.", hero_type=5, shadow="mon_archives_normal_6109.png", shadow_unlock="mon_archives_shadow_6109.png", dangerous=2, skill_list={298780,300483,300486,3004,300401}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,5}
},
	[3]={ model="6105", name="Mighty Maiden", english="Corina", story="An infected human girl wears a comfortable, loose dress. She might have once been innocent and lively or gentle and introverted, but after contamination and mutation, she lost her humanity, now only violent and cruel. If you feel mercy for her, please handle her swiftly and try not to dirty her dress.", hero_type=1, shadow="mon_archives_normal_6105.png", shadow_unlock="mon_archives_shadow_6105.png", dangerous=1, skill_list={298380,300086,3007}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[4]={ model="6121", name="Sickle Claw", english="DAVIST", story="Based on the remnants of the standard uniform, this type of mutant likely originally worked in security. They've lost self-awareness after being polluted, altering their biological Feature, with huge blade-like growths on their arms. Although they may appear agile, their moving speed is similar to a regular person, slower than expected. Their blade-arms can inflict serious damage easily, so upon encountering them, stay alert and escape.", hero_type=5, shadow="mon_archives_normal_6121.png", shadow_unlock="mon_archives_shadow_6121.png", dangerous=2, skill_list={298780,301083,301086,3010,301001}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,5}
},
	[5]={ model="6132", name="Pipe Thug", english="DAVIST", story="Thugs commonly seen in messy and chaotic neighborhoods, holding an iron pipe they got from somewhere unknown. Although they appear fierce, they actually lack combat skills; they're tough-looking on the surface but weak inside.", hero_type=1, shadow="mon_archives_normal_6132.png", shadow_unlock="mon_archives_shadow_6132.png", dangerous=1, skill_list={298180,300086,3013}, type=1, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[6]={ model="6146", name="[Chainsaw]", english="DAVIST", story="A forest work device developed by a subsidiary of Divinelight Heavy Tech, commonly used for cutting and chopping tasks. Besides basic work functions, this model is equipped with an emergency combat system for urgent situations. Users should use it cautiously based on the scenario.", hero_type=1, shadow="mon_archives_normal_6146.png", shadow_unlock="mon_archives_shadow_6146.png", dangerous=1, skill_list={298280,300086,3016}, type=2, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[7]={ model="6133", name="Club Thug", english="DAVIST", story="Thugs commonly seen in messy and chaotic neighborhoods, holding a gun they got from somewhere unknown. Although they appear fierce, they actually lack combat skills; they're tough-looking on the surface but weak inside.", hero_type=1, shadow="mon_archives_normal_6133.png", shadow_unlock="mon_archives_shadow_6133.png", dangerous=1, skill_list={298180,300086,3019}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[8]={ model="6121_d", name="Sickle Claw·Lightning", english="DAVIST", story="Based on the remnants of the standard uniform, this type of mutant likely originally worked in security. They've lost self-awareness after being polluted, altering their biological Feature, with huge blade-like growths on their arms. Although they may appear agile, their moving speed is similar to a regular person, slower than expected. Their blade-arms can inflict serious damage easily, so upon encountering them, stay alert and escape.", hero_type=5, shadow="mon_archives_normal_6121.png", shadow_unlock="mon_archives_shadow_6121.png", dangerous=2, skill_list={298780,302283,302286,3022,302201}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[9]={ model="6107", name="Canine Gorilla", english="DAVIST", story="A creature from the alien species known as [Shogger], it's hard to determine if they're closer to canine or primate. They are large and aggressive, with over 500 kg punching force making them one of the toughest enemies to deal with. Thankfully, their movement speed is slow, so if you can get away quickly, you might escape unharmed.", hero_type=6, shadow="mon_archives_normal_6107.png", shadow_unlock="mon_archives_shadow_6107.png", dangerous=3, skill_list={302580,302590,302583,302586,3025,302501,302504}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={1,2}
},
	[10]={ model="6116", name="[Workhound]", english="Hillley", story="Made from old parts, this rough construct can follow simple AI commands, often appearing in large groups. Named for its resemblance to canines, the creator is unknown.", hero_type=1, shadow="mon_archives_normal_6116.png", shadow_unlock="mon_archives_shadow_6116.png", dangerous=1, skill_list={298280,300086,3028}, type=2, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[11]={ model="6113", name="[Mountain Walker]", english="RITA", story="An outdoor work machine developed by a subsidiary of Divinelight Heavy Tech, with excellent off-road capability, perfect for work on complex terrains like mountains and mines. Besides basic exploration functions, it is equipped with an autonomous combat system for emergencies. Users should adapt usage to actual scenarios.", hero_type=1, shadow="mon_archives_normal_6113.png", shadow_unlock="mon_archives_shadow_6113.png", dangerous=1, skill_list={298280,300086,3031}, type=2, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[12]={ model="6103", name="[Patrol Mech]", english="Corina", story="Ys-3 Patrol Robot produced by Divinelight Heavy Tech, is the first mechanical humanoid weapon made in collaboration with the Burksomi Defense Department, mainly replacing patrol SWAT in dangerous raid tasks. Its introduction has alleviated the manpower strain on Burksomi's military and police, earning widespread appreciation. However, its biggest flaw is the high cost, resulting in limited numbers.", hero_type=5, shadow="mon_archives_normal_6103.png", shadow_unlock="mon_archives_shadow_6103.png", dangerous=2, skill_list={298680,303483,303486,3034,303401}, type=2, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[13]={ model="6144", name="[Storm Vortex]", english="DAVIST", story="A small security mechanical weapon developed by DragonTech, typically used for surveillance and defense work. Usually harmless but highly aggressive when the alarm is triggered. In its defense mode, it will attack anyone that gets too close—according to those who've experienced it, being shocked by four or five electric rods isn't pleasant.", hero_type=5, shadow="mon_archives_normal_6144.png", shadow_unlock="mon_archives_shadow_6144.png", dangerous=2, skill_list={298680,303783,303786,3037,303701}, type=2, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[14]={ model="6139", name="[All-Seeing]", english="DAVIST", story="A multi-purpose aerial drone developed by DragonTech, equipped with three universal track platforms that can mount different functional modules as needed, with the most common modules being Taser darts or tranquilizer bullets for law enforcement.", hero_type=5, shadow="mon_archives_normal_6139.png", shadow_unlock="mon_archives_shadow_6139.png", dangerous=2, skill_list={298680,304083,304086,3040,304001}, type=2, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[15]={ model="1802", name="Suppressor Mercenary", english="Batianta", story="A suppression-type mercenary from a certain mercenary group, equipped with a powerful handheld Gatling gun, tasked with carrying out high-risk missions. They usually wear masks and hoods, and rarely reveal their true faces, remaining mysterious even within the mercenary group. It's said that even a heavy blow to the face cannot knock their masks off.", hero_type=5, shadow="mon_archives_normal_1802.png", shadow_unlock="mon_archives_shadow_1802.png", dangerous=2, skill_list={298580,304383,304386,3043,304301}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[16]={ model="6130_h", name="Heatwave", english="DAVIST", story="Humans who have mutated after being eroded by the Void Expanse, have lost the basic biological characteristics of humans. The middle of their bodies is damaged due to high heat, which can even cause visual distortion, but this area is the core source of all their energy. —Why their bodies emit high heat is still under investigation, with initial speculation suggesting it is caused by the surrounding environment during their mutation.", hero_type=5, shadow="mon_archives_normal_6130.png", shadow_unlock="mon_archives_shadow_6130.png", dangerous=2, skill_list={298780,304683,304686,3046,304601}, type=3, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[17]={ model="6125", name="Artilleryman", english="DAVIST", story="Mutants originated from humans, whose hands have transformed into cannon-like structures. It can shoot out [energy] for attacks, with various firing modes.", hero_type=5, shadow="mon_archives_normal_6125.png", shadow_unlock="mon_archives_shadow_6125.png", dangerous=2, skill_list={298780,304983,304986,3049,304901}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[18]={ model="6309", name="Reina", english="DAVIST", story="A former senior researcher at Neoscope Inc and a biology professor at Lissugen University, turned into a monster called the [Flower of Resentment] after being injected with a certain drug. Her withered body has a kind of flawed beauty, and from the remaining human traits, she seems to still retain some human reason and rationality. But be sure not to go near her—unless you want to be torn apart by her claws.", hero_type=6, shadow="mon_archives_normal_6309.png", shadow_unlock="mon_archives_shadow_6309.png", dangerous=3, skill_list={305280,305290,305283,305286,3052,305201,305204}, type=3, special="Focus Back Row", speed="", element={0}, weak_point={0,1}
},
	[19]={ model="6115", name="Impact Drill", english="DAVIST", story="Members of the Coordinator Sect, likely low in rank, primarily work on construction projects for the cult. Their mutated hand structure can penetrate solid building exteriors and surfaces, excelling at drilling. They retain human self-awareness but are silent, unresponsive to communication. Nonetheless, escape if encountered to avoid attack.", hero_type=1, shadow="mon_archives_normal_6115.png", shadow_unlock="mon_archives_shadow_6115.png", dangerous=1, skill_list={298380,300086,3055}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[20]={ model="6110", name="Slasher Fiend", english="DAVIST", story="Members of the Coordinator Sect. There are many reasons to join them: seeking sustenance, seeking shelter, or simply wanting to vent dissatisfaction. [Slasher Fiend] clearly belongs to the latter. They are keen on blood, enjoy brutal killing, and like to dismember and display their prey in cruel ways—even within the Coordinators' camp, their actions have caused displeasure among many members.", hero_type=5, shadow="mon_archives_normal_6110.png", shadow_unlock="mon_archives_shadow_6110.png", dangerous=2, skill_list={298780,305883,305886,3058,305801}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[21]={ model="6128", name="Disruptor", english="DAVIST", story="A creature from the alien species known as [Shogger], resembles arthropods from Taino Star, supported by thin legs with a core-like trunk that emits energy interfering with electronics, similar to electromagnetic waves according to studies.", hero_type=1, shadow="mon_archives_normal_6128.png", shadow_unlock="mon_archives_shadow_6128.png", dangerous=1, skill_list={298480,300086,3061}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[22]={ model="6112", name="Handmaiden", english="DAVIST", story="From the back, one might easily mistake her for an elegant and intellectual ordinary woman, but she's actually one of the fierce alien creatures from [Shogger]. She attacks using mysterious energy and controls the [dual swords] around her, while her graceful and agile form makes her appear quite... beautiful. Even in battle, she maintains her elegance at all times, perhaps it's just instinct.", hero_type=5, shadow="mon_archives_normal_6112.png", shadow_unlock="mon_archives_shadow_6112.png", dangerous=2, skill_list={298880,306483,306486,3064,306401}, type=4, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[23]={ model="6120", name="Stone Dragonfly", english="DAVIST", story="A creature from the alien species known as [Shogger], resembles a dragonfly from the Taino Star, but its body is made of an unknown material similar to rocks. It moves extremely fast and likes to appear in groups. Even large enemies find it hard to withstand the swarming stone dragonflies.", hero_type=1, shadow="mon_archives_normal_6120.png", shadow_unlock="mon_archives_shadow_6120.png", dangerous=1, skill_list={298480,300086,3067}, type=4, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[24]={ model="6127", name="Drill Vehicle", english="DAVIST", story="A mutant whose upper body has mutated into a drill-shaped form, capable of penetrating through tough buildings and surfaces, with immense destructive power. It attacks by using its drill-like head to [drill] its target to death. Due to the brutal and excessively bloody nature of this attack, there's only one way to handle such a mutant: complete destruction.", hero_type=5, shadow="mon_archives_normal_6127.png", shadow_unlock="mon_archives_shadow_6127.png", dangerous=2, skill_list={298780,307083,307086,3070,307001}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[25]={ model="6126", name="Swift Vermin", english="Alice", story="A certain large insect, widely distributed across various areas of the Taino Star, appears in this form after being tainted. They often appear in clusters, and when you see a swift vermin, there are definitely over twenty others of its kind nearby. They emit an unpleasant 'chit-chit' sound and will pounce on people. For some reason, they create immense psychological pressure on those who encounter them.", hero_type=1, shadow="mon_archives_normal_6126.png", shadow_unlock="mon_archives_shadow_6126.png", dangerous=1, skill_list={298380,300086,3073}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[26]={ model="6310", name="Flandre", english="DAVIST", story="A cadre of the mysterious organization [Coordinator Sect,] codenamed [Smoldering Wings,] has orchestrated numerous malicious incidents behind the scenes in Lissugen. Don't be fooled by her sweet and charming appearance.", hero_type=6, shadow="mon_archives_normal_6310.png", shadow_unlock="mon_archives_shadow_6310.png", dangerous=3, skill_list={307680,307690,307683,307686,3076,307601,307604}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={1,4}
},
	[27]={ model="6135", name="Shield Hammer", english="Batianta", story="Trained professionals equipped with riot shields and breaching hammers, can easily break through enemy lines with support from remote firepower.", hero_type=1, shadow="mon_archives_normal_6135.png", shadow_unlock="mon_archives_shadow_6135.png", dangerous=1, skill_list={298180,300086,3079}, type=1, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[28]={ model="6134", name="Rifleman", english="Flanbine", story="Professionally trained individuals, equipped with electromagnetic assault rifles and light armor, are not opponents that ordinary civilians can contend with.", hero_type=1, shadow="mon_archives_normal_6134.png", shadow_unlock="mon_archives_shadow_6134.png", dangerous=1, skill_list={298180,300086,3082}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[29]={ model="6122", name="Assault Mercenary", english="DAVIST", story="The assault-type mercenaries of a certain mercenary group, use long spears and excel at close combat, taking enemies' heads at close range. However, assault-type mercenaries are usually composed of women, who possess a good figure and have silver hair. Although they look exactly alike, like cloned replicas, they are still highly admired and loved within the mercenary group. However, they usually only follow orders from the mercenary group leader and disregard everyone else.", hero_type=5, shadow="mon_archives_normal_6122.png", shadow_unlock="mon_archives_shadow_6122.png", dangerous=2, skill_list={298580,308583,308586,3085,308501}, type=1, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[30]={ model="6101", name="[Surveillance Fly]", english="DAVIST", story="The TxP09 flight monitor produced by Divinelight Heavy Tech, Feature a design inspired by the appearance of a fly. Besides functioning as a monitor, it has some combat capabilities and can be deployed as a combat unit when necessary, although its combat strength is not high. Users are advised to use it cautiously.", hero_type=1, shadow="mon_archives_normal_6101.png", shadow_unlock="mon_archives_shadow_6101.png", dangerous=1, skill_list={298280,300086,3088}, type=2, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[31]={ model="1801", name="Scout Mercenary", english="Flanbine", story="Mercenaries drift between cities, their faces perpetually hidden behind masks to conceal their identities. Lightning-fast and relentless, once they've locked onto a target, escape becomes nearly impossible. Rumor has it their creed is simple: Name the job—we'll take it. For the right price.", hero_type=5, shadow="mon_archives_normal_1801.png", shadow_unlock="mon_archives_shadow_1801.png", dangerous=2, skill_list={298580,309183,309186,3091,309101}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[32]={ model="6104_b", name="Clawed Clerk·Ice", english="Kalan Lisa", story="Mutants commonly found around fortress cities—The remnants of business suits, neckties, and leather shoes still visible on their twisted forms tell their tragic origin—these were once white-collar workers toiling in cubicles. Perhaps moments before contamination, they had just closed a deal, finalized a proposal, received a promotion... or were rushing home to loved ones... Until the unknown catastrophe struck, ending everything in an instant.", hero_type=1, shadow="mon_archives_normal_6104.png", shadow_unlock="mon_archives_shadow_6104.png", dangerous=1, skill_list={298380,309483,309486,3094}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[33]={ model="6117", name="Third Hand", english="DAVIST", story="Members of the Coordinator Sect, likely low-ranked, are often seen in errands or simple combat missions. Don't overlook their combat abilities due to their rank; the code [Third Hand] shows how tricky and troublesome their third polluted hand is.", hero_type=5, shadow="mon_archives_normal_6117.png", shadow_unlock="mon_archives_shadow_6117.png", dangerous=2, skill_list={298780,309783,309786,3097,309701}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[34]={ model="6109_b", name="Hammer Man·Ice", english="DAVIST", story="Originally workers from the mining facilities, these individuals underwent grotesque transformation after exposure to the Void Expanse during the Anchor Panic. Their mutated epidermal growths and aberrant biological structures indicate Stage III infection. Though clumsy in movement, they retain terrifying proficiency with mining hammers—a grim reminder of their former profession. Unprepared travelers are strongly advised to disengage.", hero_type=5, shadow="mon_archives_normal_6109.png", shadow_unlock="mon_archives_shadow_6109.png", dangerous=2, skill_list={298780,310083,310086,3100,310001}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[35]={ model="6308", name="Famous Sword Lancelot", english="DAVIST", story="Dean's Sword", hero_type=5, shadow="mon_archives_normal_6308.png", shadow_unlock="mon_archives_shadow_6308.png", dangerous=2, skill_list={298780,310383,310386,3103,310301}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[36]={ model="6133_b", name="Club Thug·Ice", english="DAVIST", story="Thugs commonly seen in messy and chaotic neighborhoods, holding a gun they got from somewhere unknown. Although they appear fierce, they actually lack combat skills; they're tough-looking on the surface but weak inside.", hero_type=1, shadow="mon_archives_normal_6133.png", shadow_unlock="mon_archives_shadow_6133.png", dangerous=1, skill_list={298180,310683,310686,3106}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[37]={ model="6129", name="Phantom Lion", english="DAVIST", story="A contaminated four-legged beast, its original form is unrecognizable. The black sludge of pollutants covers its entire body, giving it a lion-like appearance. Where its head once was, there's a growth resembling a ghostly face, with the power to control elements. It feeds by sucking through tentacles that resemble mane.", hero_type=5, shadow="mon_archives_normal_6129.png", shadow_unlock="mon_archives_shadow_6129.png", dangerous=2, skill_list={298780,310983,310986,3109,310901}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[38]={ model="6305", name="Dean", english="DAVIST", story="Dean·Lancelot, once the head of the renowned Lancelot family in Joshburg, unfortunately passed away after an accident. When Dean appeared in the world again, he had become the [Iron Knight] of the Coordinator Sect, clearing all obstacles in the way for the order—", hero_type=6, shadow="mon_archives_normal_6305.png", shadow_unlock="mon_archives_shadow_6305.png", dangerous=3, skill_list={311280,311290,311283,311286,3112,311201,311204}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={1,2}
},
	[39]={ model="6134_h", name="Rifleman·Fire", english="Flanbine", story="Professionally trained individuals, equipped with electromagnetic assault rifles and light armor, are not opponents that ordinary civilians can contend with.", hero_type=1, shadow="mon_archives_normal_6134.png", shadow_unlock="mon_archives_shadow_6134.png", dangerous=1, skill_list={298180,311583,311586,3115}, type=1, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[40]={ model="6145", name="RET C.D. Soldier", english="Kalan Lisa", story="Soldiers serving in special forces, are professionally trained experts to resist enemy invasions, often appearing in frontline war zones. They provide strong shields for themselves and allied forces, ensuring combat safety.", hero_type=5, shadow="mon_archives_normal_6145.png", shadow_unlock="mon_archives_shadow_6145.png", dangerous=2, skill_list={298580,311883,311886,3118,311801}, type=1, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[41]={ model="6132_h", name="Pipe Thug·Fire", english="DAVIST", story="Thugs commonly seen in messy and chaotic neighborhoods, holding an iron pipe they got from somewhere unknown. Although they appear fierce, they actually lack combat skills; they're tough-looking on the surface but weak inside.", hero_type=1, shadow="mon_archives_normal_6132.png", shadow_unlock="mon_archives_shadow_6132.png", dangerous=1, skill_list={298180,312183,312186,3121}, type=1, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[42]={ model="6125_h", name="Artilleryman·Fire", english="DAVIST", story="Mutants originated from humans, whose hands have transformed into cannon-like structures. It can shoot out [energy] for attacks, with various firing modes.", hero_type=5, shadow="mon_archives_normal_6125.png", shadow_unlock="mon_archives_shadow_6125.png", dangerous=2, skill_list={298780,312483,312486,3124,312401}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[43]={ model="6126_h", name="Swift Vermin·Fire", english="Alice", story="A certain large insect, widely distributed across various areas of the Taino Star, appears in this form after being tainted. They often appear in clusters, and when you see a swift vermin, there are definitely over twenty others of its kind nearby. They emit an unpleasant 'chit-chit' sound and will pounce on people. For some reason, they create immense psychological pressure on those who encounter them.", hero_type=1, shadow="mon_archives_normal_6126.png", shadow_unlock="mon_archives_shadow_6126.png", dangerous=1, skill_list={298380,312783,312786,3127}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[44]={ model="6121_h", name="Sickle Claw·Fire", english="DAVIST", story="Based on the remnants of the standard uniform, this type of mutant likely originally worked in security. They've lost self-awareness after being polluted, altering their biological Feature, with huge blade-like growths on their arms. Although they may appear agile, their moving speed is similar to a regular person, slower than expected. Their blade-arms can inflict serious damage easily, so upon encountering them, stay alert and escape.", hero_type=5, shadow="mon_archives_normal_6121.png", shadow_unlock="mon_archives_shadow_6121.png", dangerous=2, skill_list={298780,313083,313086,3130,313001}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[45]={ model="6115_d", name="Impact Drill·Lightning", english="DAVIST", story="Members of the Coordinator Sect, likely low in rank, primarily work on construction projects for the cult. Their mutated hand structure can penetrate solid building exteriors and surfaces, excelling at drilling. They retain human self-awareness but are silent, unresponsive to communication. Nonetheless, escape if encountered to avoid attack.", hero_type=1, shadow="mon_archives_normal_6115.png", shadow_unlock="mon_archives_shadow_6115.png", dangerous=1, skill_list={298380,313383,313386,3133}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[46]={ model="6109_d", name="Hammer Man·Lightning", english="DAVIST", story="Originally workers from the mining facilities, these individuals underwent grotesque transformation after exposure to the Void Expanse during the Anchor Panic. Their mutated epidermal growths and aberrant biological structures indicate Stage III infection. Though clumsy in movement, they retain terrifying proficiency with mining hammers—a grim reminder of their former profession. Unprepared travelers are strongly advised to disengage.", hero_type=5, shadow="mon_archives_normal_6109.png", shadow_unlock="mon_archives_shadow_6109.png", dangerous=2, skill_list={298780,313683,313686,3136,313601}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[47]={ model="6116_d", name="[Workhound]·Lightning", english="Hillley", story="Made from old parts, this rough construct can follow simple AI commands, often appearing in large groups. Named for its resemblance to canines, the creator is unknown.", hero_type=1, shadow="mon_archives_normal_6116.png", shadow_unlock="mon_archives_shadow_6116.png", dangerous=1, skill_list={298280,313983,313986,3139}, type=2, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[48]={ model="6111", name="[Forest Ranger]", english="Alice", story="Low-intelligence robots first appeared in Selevie, designed to replace humans in forest patrols. People added simple decorations reflecting local Feature. They're short, not fast movers, but their arrows are speedy and hit targets precisely.", hero_type=5, shadow="mon_archives_normal_6111.png", shadow_unlock="mon_archives_shadow_6111.png", dangerous=2, skill_list={298680,314283,314286,3142,314201}, type=2, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[49]={ model="6105_d", name="Mighty Maiden·Lightning", english="Corina", story="An infected human girl wears a comfortable, loose dress. She might have once been innocent and lively or gentle and introverted, but after contamination and mutation, she lost her humanity, now only violent and cruel. If you feel mercy for her, please handle her swiftly and try not to dirty her dress.", hero_type=1, shadow="mon_archives_normal_6105.png", shadow_unlock="mon_archives_shadow_6105.png", dangerous=1, skill_list={298380,314583,314586,3145}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[50]={ model="6101_d", name="[Surveillance Fly]·Lightning", english="DAVIST", story="The TxP09 flight monitor produced by Divinelight Heavy Tech, Feature a design inspired by the appearance of a fly. Besides functioning as a monitor, it has some combat capabilities and can be deployed as a combat unit when necessary, although its combat strength is not high. Users are advised to use it cautiously.", hero_type=1, shadow="mon_archives_normal_6101.png", shadow_unlock="mon_archives_shadow_6101.png", dangerous=1, skill_list={298280,314883,314886,3148}, type=2, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[51]={ model="6117_d", name="Third Hand·Lightning", english="DAVIST", story="Members of the Coordinator Sect, likely low-ranked, are often seen in errands or simple combat missions. Don't overlook their combat abilities due to their rank; the code [Third Hand] shows how tricky and troublesome their third polluted hand is.", hero_type=5, shadow="mon_archives_normal_6117.png", shadow_unlock="mon_archives_shadow_6117.png", dangerous=2, skill_list={298780,315183,315186,3151,315101}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[52]={ model="6136", name="Wheeled Angel", english="DAVIST", story="Shogger resembling the ancient legendary creature 'Angel' from Taino Star, surrounded by abnormal flames, with three wheel-like objects spinning constantly. It seems to have some intelligence, able to emit sounds like [language,] but nobody understands it.", hero_type=5, shadow="mon_archives_normal_6136.png", shadow_unlock="mon_archives_shadow_6136.png", dangerous=2, skill_list={298880,315483,315486,3154,315401}, type=4, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[53]={ model="6311", name="Ming", english="DAVIST", story="The head of the Anti-Skyborne Barriers organization [ULFT] in Lissugen, is bold and fiery, easily spotted with her striking red hair. Despite her youth, her subordinates call her [Big Sis.]", hero_type=6, shadow="mon_archives_normal_6311.png", shadow_unlock="mon_archives_shadow_6311.png", dangerous=3, skill_list={315780,315790,315783,315786,3157,315701,315704}, type=1, special="Focus Opposite", speed="", element={0}, weak_point={2,3}
},
	[54]={ model="6104_g", name="Clawed Clerk·Quantum", english="Kalan Lisa", story="Mutants commonly found around fortress cities—The remnants of business suits, neckties, and leather shoes still visible on their twisted forms tell their tragic origin—these were once white-collar workers toiling in cubicles. Perhaps moments before contamination, they had just closed a deal, finalized a proposal, received a promotion... or were rushing home to loved ones... Until the unknown catastrophe struck, ending everything in an instant.", hero_type=1, shadow="mon_archives_normal_6104.png", shadow_unlock="mon_archives_shadow_6104.png", dangerous=1, skill_list={298380,316083,316086,3160}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[55]={ model="6121_g", name="Sickle Claw·Quantum", english="DAVIST", story="Based on the remnants of the standard uniform, this type of mutant likely originally worked in security. They've lost self-awareness after being polluted, altering their biological Feature, with huge blade-like growths on their arms. Although they may appear agile, their moving speed is similar to a regular person, slower than expected. Their blade-arms can inflict serious damage easily, so upon encountering them, stay alert and escape.", hero_type=5, shadow="mon_archives_normal_6121.png", shadow_unlock="mon_archives_shadow_6121.png", dangerous=2, skill_list={298780,316383,316386,3163,316301}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[56]={ model="6128_g", name="Disruptor·Quantum", english="DAVIST", story="A creature from the alien species known as [Shogger], resembles arthropods from Taino Star, supported by thin legs with a core-like trunk that emits energy interfering with electronics, similar to electromagnetic waves according to studies.", hero_type=1, shadow="mon_archives_normal_6128.png", shadow_unlock="mon_archives_shadow_6128.png", dangerous=1, skill_list={298480,316683,316686,3166}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[57]={ model="6102", name="Dachshund", english="DAVIST", story="A creature from the alien species known as [Shogger], resembles canine creatures from Taino Star. Covered in metal and stone-like unknown substances, they move in packs, their paws like steel blades, moving unpredictably and causing great harm.", hero_type=5, shadow="mon_archives_normal_6102.png", shadow_unlock="mon_archives_shadow_6102.png", dangerous=2, skill_list={298880,316983,316986,3169,316901}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[58]={ model="6119", name="Box Scorpion", english="Bianno", story="A creature from the alien species known as [Shogger], looks like the scorpion from Taino Star, but more like a box with a long tail. The sting from its pustule-like tail is poisonous, causing unbearable pain and possibly death.", hero_type=1, shadow="mon_archives_normal_6119.png", shadow_unlock="mon_archives_shadow_6119.png", dangerous=1, skill_list={298480,300086,3172}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[59]={ model="6118", name="Serpent Drake", english="DAVIST", story="A creature from the alien species known as [Shogger], looks like a legendary [flying snake.] It seems to have high intellect, not attacking recklessly, striking at the perfect moment, fitting the stereotype of a snake or dragon.", hero_type=5, shadow="mon_archives_normal_6118.png", shadow_unlock="mon_archives_shadow_6118.png", dangerous=2, skill_list={298880,317583,317586,3175,317501}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[60]={ model="6114", name="Cosmic Squid", english="Alicia", story="A creature from the alien species known as [Shogger], resembles a squid but—unlike a squid—this thing is absolutely not edible!", hero_type=1, shadow="mon_archives_normal_6114.png", shadow_unlock="mon_archives_shadow_6114.png", dangerous=1, skill_list={298480,300086,3178}, type=4, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[61]={ model="6123", name="Wolf Hunter", english="DAVIST", story="A creature from the alien species known as [Shogger], resembles canine creatures from Taino Star with short limbs and large [heads] surrounded by complex structures. Reports from battles suggest the head is their [death point.]", hero_type=5, shadow="mon_archives_normal_6123.png", shadow_unlock="mon_archives_shadow_6123.png", dangerous=2, skill_list={298880,318183,318186,3181,318101}, type=4, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[62]={ model="6137", name="Grotesque Puppet", english="DAVIST", story="A Shogger resembling man-made clay figurines, appears in groups, firing deadly rays from its [mouth] and emitting strange sounds. Some researchers think these sounds are Shogger language, but this idea isn't backed by evidence or support.", hero_type=1, shadow="mon_archives_normal_6137.png", shadow_unlock="mon_archives_shadow_6137.png", dangerous=1, skill_list={298480,300086,3184}, type=4, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[63]={ model="6138", name="Star of Mother and Child", english="DAVIST", story="A Shogger composed of two sub-units, with one looking like a woman and the other a child. Their attack style resembles [mother-child play] rather than aggression.", hero_type=5, shadow="mon_archives_normal_6138.png", shadow_unlock="mon_archives_shadow_6138.png", dangerous=2, skill_list={298880,318783,318786,3187,318701}, type=4, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[64]={ model="6124", name="Mountain Behemoth", english="DAVIST", story="A creature from the alien species known as [Shogger], has a shell composed of stacked crystal blocks, with individual floating crystal fragments nearby. It can manipulate gravity, causing ground collapses and building destruction in its path. Combat reports suggest attacking its unarmored belly first.", hero_type=5, shadow="mon_archives_normal_6124.png", shadow_unlock="mon_archives_shadow_6124.png", dangerous=2, skill_list={298880,319083,319086,3190,319001}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[65]={ model="6115_g", name="Impact Drill·Quantum", english="DAVIST", story="Members of the Coordinator Sect, likely low in rank, primarily work on construction projects for the cult. Their mutated hand structure can penetrate solid building exteriors and surfaces, excelling at drilling. They retain human self-awareness but are silent, unresponsive to communication. Nonetheless, escape if encountered to avoid attack.", hero_type=1, shadow="mon_archives_normal_6115.png", shadow_unlock="mon_archives_shadow_6115.png", dangerous=1, skill_list={298380,319383,319386,3193}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[66]={ model="6117_g", name="Third Hand·Quantum", english="DAVIST", story="Members of the Coordinator Sect, likely low-ranked, are often seen in errands or simple combat missions. Don't overlook their combat abilities due to their rank; the code [Third Hand] shows how tricky and troublesome their third polluted hand is.", hero_type=5, shadow="mon_archives_normal_6117.png", shadow_unlock="mon_archives_shadow_6117.png", dangerous=2, skill_list={298780,319683,319686,3196,319601}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[67]={ model="6303", name="Scorpio", english="DAVIST", story="A Shogger individual shrouded in mystery, unlike common Shoggers, it not only shows intelligence but can also interfere with surrounding space to some extent. According to Leistance Security Bureau, this might be a high-level Shogger species, possibly even a leader, but specifics remain unclear.", hero_type=6, shadow="mon_archives_normal_6303.png", shadow_unlock="mon_archives_shadow_6303.png", dangerous=3, skill_list={319980,319990,319983,319986,3199,319901,319904}, type=4, special="Focus Opposite Front Row", speed="", element={0}, weak_point={2,5}
},
	[68]={ model="6307", name="Dean·Ultimate", english="DAVIST", story="Dean·Lancelot, once the head of the renowned Lancelot family in Joshburg, unfortunately passed away after an accident. When Dean appeared in the world again, he had become the [Iron Knight] of the Coordinator Sect, clearing all obstacles in the way for the order—", hero_type=6, shadow="mon_archives_normal_6307.png", shadow_unlock="mon_archives_shadow_6307.png", dangerous=3, skill_list={400180,400190,400183,400186,4001,400101,400104}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={1,2}
},
	[69]={ model="6131", name="Alien Sword", english="DAVIST", story="Dean's Sword", hero_type=5, shadow="mon_archives_normal_6131.png", shadow_unlock="mon_archives_shadow_6131.png", dangerous=2, skill_list={298780,400483,400486,4004,400401}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={1,4}
},
	[73]={ model="6301", name="Iron Thorn", english="DAVIST", story="Members of the Coordinator Sect, low-ranked, are often put on advance sabotage tasks. Contamination has resulted in severe mutations on various bodily parts, including but not limited to skin deformities and abnormal surface structures—arms sprouting thorn-like parts. They retain human consciousness but suffer from intense mental contamination, showing long-term insanity and pathological behavior, with aggressive and destructive tendencies.", hero_type=6, shadow="mon_archives_normal_6301.png", shadow_unlock="mon_archives_shadow_6301.png", dangerous=3, skill_list={400880,400890,400883,400886,4008,400801,400804}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={1,4}
},
	[74]={ model="6302", name="Sword Angel", english="DAVIST", story="A Shogger slightly resembling angels from ancient tales, attacking with a [great sword] made of the same material as its body. It appears to have intelligence, emitting rhythmical sounds from its [head.] Some say it's Shogger language but there's been no proof.", hero_type=6, shadow="mon_archives_normal_6302.png", shadow_unlock="mon_archives_shadow_6302.png", dangerous=3, skill_list={401180,401190,401183,401186,4011,401101,401104}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[75]={ model="6304", name="Peril Beast", english="DAVIST", story="A creature from the alien species known as [Shogger] somewhat resembles a tiger from Taino Star, missing visible facial Feature but with a mouth that absorbs energy. Its four [tails] can emit energy and heat rays, causing great destruction. When attacked directly, it forms a protective barrier; breaking through requires much stronger force, making it one of the more troublesome Shogger types known.", hero_type=6, shadow="mon_archives_normal_6304.png", shadow_unlock="mon_archives_shadow_6304.png", dangerous=3, skill_list={401480,401490,401483,401486,4014,401401,401404}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={2,5}
},
	[76]={ model="6106", name="Bio-Enhanced·Male", english="DAVIST", story="A bio-enhanced human illegally modified multiple times, the modifier inserted many experimental mechanical components not approved for use. Though it severely increased combat ability, it greatly damaged normal human body structure. Due to the modifier's neglect for body restoration, it's held together by bandages—[as long as you're dressed well, no one will know what you're,] the modifier advised the experimenter.", hero_type=5, shadow="mon_archives_normal_6106.png", shadow_unlock="mon_archives_shadow_6106.png", dangerous=2, skill_list={298580,401783,401786,4017,401701}, type=1, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[77]={ model="6108", name="Bio-Enhanced·Female", english="DAVIST", story="A bio-enhanced human illegally modified multiple times, modified with many out-of-spec components increasing physique. To keep a human appearance due to the modifier's personal taste, various illegal recovery liquids were injected. The face was intentionally damaged beyond recognition, so bandages are worn constantly.", hero_type=5, shadow="mon_archives_normal_6108.png", shadow_unlock="mon_archives_shadow_6108.png", dangerous=2, skill_list={298580,402083,402086,4020,402001}, type=1, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[78]={ model="6141", name="RubinⅩ", english="Alicia", story="The 10th-generation product of the advanced mechanical dog series [Rubin], used for field exploration, small-scale transportation, home defense, and personal companionship.Mental system upgrade makes thinking comparable to a twelve-year-old human.", hero_type=5, shadow="mon_archives_normal_6141.png", shadow_unlock="mon_archives_shadow_6141.png", dangerous=2, skill_list={298680,402383,402386,4023,402301}, type=2, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[79]={ model="6143", name="[Phantom Soldier]", english="Bianno", story="After the Shogger invasion war, nations on Taino Star began rebuilding the world, resulting in frequent conflicts and creation of new weapons. [Phantom Soldier] emerged during this period. As a versatile manned mech, it brings Divinelight Heavy Tech immense profit.", hero_type=5, shadow="mon_archives_normal_6143.png", shadow_unlock="mon_archives_shadow_6143.png", dangerous=2, skill_list={298680,402683,402686,4026,402601}, type=2, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[80]={ model="6140", name="[Swift Feet]", english="DAVIST", story="Amulti-purpose ground drone developed by DragonTech, equipped with two universal module platforms, can be fitted with different function modules as needed. The most common modules are for security, like taser darts or tranquilizer rounds, designed to pair with the company's [All-Seeing].", hero_type=1, shadow="mon_archives_normal_6140.png", shadow_unlock="mon_archives_shadow_6140.png", dangerous=1, skill_list={298280,300086,4029}, type=2, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[81]={ model="6150_b", name="Hyena Stone Lizard", english="DAVIST", story="A Taino Star lizard species mutated from Void Particles contamination, covered in distorted crystals, can dig rapidly underground. Despite being mutants, they're unexpectedly cowardly, making a quick escape when outmatched.", hero_type=5, shadow="mon_archives_normal_6150.png", shadow_unlock="mon_archives_shadow_6150.png", dangerous=2, skill_list={403280,403283,403286,4032,403201}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[82]={ model="6149", name="Mutant Mechanic", english="Alice", story="Used to work at Kroward Factory, contaminated by a sudden Void Particles storm and transformed into a mutant. They lost rationality and attacked colleagues indiscriminately, now only able to rest in peace through weapons.", hero_type=1, shadow="mon_archives_normal_6149.png", shadow_unlock="mon_archives_shadow_6149.png", dangerous=1, skill_list={403580,300086,4035}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[83]={ model="6149_b", name="Mutant Mechanic·Ice", english="Alice", story="Used to work at Kroward Factory, contaminated by a sudden Void Particles storm and transformed into a mutant. They lost rationality and attacked colleagues indiscriminately, now only able to rest in peace through weapons.", hero_type=1, shadow="mon_archives_normal_6149.png", shadow_unlock="mon_archives_shadow_6149.png", dangerous=1, skill_list={403880,403883,403886,4038}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[84]={ model="6149_h", name="Mutant Mechanic·Fire", english="Alice", story="Used to work at Kroward Factory, contaminated by a sudden Void Particles storm and transformed into a mutant. They lost rationality and attacked colleagues indiscriminately, now only able to rest in peace through weapons.", hero_type=1, shadow="mon_archives_normal_6149.png", shadow_unlock="mon_archives_shadow_6149.png", dangerous=1, skill_list={404180,404183,404186,4041}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[85]={ model="6149_z", name="Mutant Mechanic·Natural", english="Alice", story="Used to work at Kroward Factory, contaminated by a sudden Void Particles storm and transformed into a mutant. They lost rationality and attacked colleagues indiscriminately, now only able to rest in peace through weapons.", hero_type=1, shadow="mon_archives_normal_6149.png", shadow_unlock="mon_archives_shadow_6149.png", dangerous=1, skill_list={404480,404483,404486,4044}, type=3, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[86]={ model="6147", name="Mutant Machinist", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. Before the mutation, they worked as a mechanical repairman, always carrying a bunch of tools. After turning into a monster, these tools also [grew] on their body.", hero_type=5, shadow="mon_archives_normal_6147.png", shadow_unlock="mon_archives_shadow_6147.png", dangerous=2, skill_list={404780,404783,404786,4047,404701}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[87]={ model="6147_d", name="Mutant Machinist·Lightning", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. Before the mutation, they worked as a mechanical repairman, always carrying a bunch of tools. After turning into a monster, these tools also [grew] on their body.", hero_type=5, shadow="mon_archives_normal_6147.png", shadow_unlock="mon_archives_shadow_6147.png", dangerous=2, skill_list={298780,405083,405086,4050,405001}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[88]={ model="6147_g", name="Mutant Machinist·Quantum", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. Before the mutation, they worked as a mechanical repairman, always carrying a bunch of tools. After turning into a monster, these tools also [grew] on their body.", hero_type=5, shadow="mon_archives_normal_6147.png", shadow_unlock="mon_archives_shadow_6147.png", dangerous=2, skill_list={298780,405383,405386,4053,405301}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[89]={ model="6147_h", name="Mutant Machinist·Fire", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. Before the mutation, they worked as a mechanical repairman, always carrying a bunch of tools. After turning into a monster, these tools also [grew] on their body.", hero_type=5, shadow="mon_archives_normal_6147.png", shadow_unlock="mon_archives_shadow_6147.png", dangerous=2, skill_list={298780,405683,405686,4056,405601}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[90]={ model="6148", name="Mutant Miner", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. He wields what was once his most handy tool, now turned into a deadly weapon—the pickaxe, attacking all living creatures indiscriminately.", hero_type=5, shadow="mon_archives_normal_6148.png", shadow_unlock="mon_archives_shadow_6148.png", dangerous=2, skill_list={298780,405983,405986,4059,405901}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[91]={ model="6148_b", name="Mutant Miner·Ice", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. He wields what was once his most handy tool, now turned into a deadly weapon—the pickaxe, attacking all living creatures indiscriminately.", hero_type=5, shadow="mon_archives_normal_6148.png", shadow_unlock="mon_archives_shadow_6148.png", dangerous=2, skill_list={298780,406283,406286,4062,406201}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[92]={ model="6148_d", name="Mutant Miner·Lightning", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. He wields what was once his most handy tool, now turned into a deadly weapon—the pickaxe, attacking all living creatures indiscriminately.", hero_type=5, shadow="mon_archives_normal_6148.png", shadow_unlock="mon_archives_shadow_6148.png", dangerous=2, skill_list={298780,406583,406586,4065,406501}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[93]={ model="6148_h", name="Mutant Miner·Fire", english="DAVIST", story="Used to work in the Crystal Mine, but was contaminated by a sudden Void Particles storm and transformed into a mutant. He wields what was once his most handy tool, now turned into a deadly weapon—the pickaxe, attacking all living creatures indiscriminately.", hero_type=5, shadow="mon_archives_normal_6148.png", shadow_unlock="mon_archives_shadow_6148.png", dangerous=2, skill_list={298780,406883,406886,4068,406801}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[94]={ model="6312", name="Lucas", english="DAVIST", story="The former most trusted aide of Kroward's Foreign Minister Leoni Hastings, has now turned into a vengeful monster.", hero_type=6, shadow="mon_archives_normal_6312.png", shadow_unlock="mon_archives_shadow_6312.png", dangerous=3, skill_list={407180,407190,407183,407186,4071,407101,407104}, type=3, special="Focus Opposite Front Row", speed="", element={0}, weak_point={2,5}
},
	[95]={ model="6155", name="Devourer Banyan", english="Alice", story="Common plants in the Selevie Forest, grow mainly near water. Even after being polluted, they retain their original shape and vibrant colors, capable of shooting energy attacks from their stamens at anything that approaches. Beautiful, but deadly.", hero_type=1, shadow="mon_archives_normal_6155.png", shadow_unlock="mon_archives_shadow_6155.png", dangerous=1, skill_list={407480,300086,4074}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[96]={ model="6155_b", name="Devourer Banyan·Ice", english="Alice", story="Common plants in the Selevie Forest, grow mainly near water. Even after being polluted, they retain their original shape and vibrant colors, capable of shooting energy attacks from their stamens at anything that approaches. Beautiful, but deadly.", hero_type=1, shadow="mon_archives_normal_6155.png", shadow_unlock="mon_archives_shadow_6155.png", dangerous=1, skill_list={407480,407783,407786,4077}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[97]={ model="6155_d", name="Devourer Banyan·Lightning", english="Alice", story="Common plants in the Selevie Forest, grow mainly near water. Even after being polluted, they retain their original shape and vibrant colors, capable of shooting energy attacks from their stamens at anything that approaches. Beautiful, but deadly.", hero_type=1, shadow="mon_archives_normal_6155.png", shadow_unlock="mon_archives_shadow_6155.png", dangerous=1, skill_list={407480,408083,408086,4080}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[98]={ model="6155_h", name="Devourer Banyan·Fire", english="Alice", story="Common plants in the Selevie Forest, grow mainly near water. Even after being polluted, they retain their original shape and vibrant colors, capable of shooting energy attacks from their stamens at anything that approaches. Beautiful, but deadly.", hero_type=1, shadow="mon_archives_normal_6155.png", shadow_unlock="mon_archives_shadow_6155.png", dangerous=1, skill_list={407480,408383,408386,4083}, type=3, special="Focus Opposite", speed="", element={0}, weak_point={0,3}
},
	[99]={ model="6156", name="Long Grass", english="DAVIST", story="Plants that used to grow widely in the Selevie Marsh, after being polluted, take on forms that disguise themselves as normal plants in the marsh, becoming highly aggressive once touched by any creatures.", hero_type=1, shadow="mon_archives_normal_6156.png", shadow_unlock="mon_archives_shadow_6156.png", dangerous=1, skill_list={298480,300086,4086}, type=4, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[100]={ model="6156_b", name="Long Grass·Ice", english="DAVIST", story="Plants that used to grow widely in the Selevie Marsh, after being polluted, take on forms that disguise themselves as normal plants in the marsh, becoming highly aggressive once touched by any creatures.", hero_type=1, shadow="mon_archives_normal_6156.png", shadow_unlock="mon_archives_shadow_6156.png", dangerous=1, skill_list={298480,408983,408986,4089}, type=4, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[101]={ model="6156_d", name="Long Grass·Lightning", english="DAVIST", story="Plants that used to grow widely in the Selevie Marsh, after being polluted, take on forms that disguise themselves as normal plants in the marsh, becoming highly aggressive once touched by any creatures.", hero_type=1, shadow="mon_archives_normal_6156.png", shadow_unlock="mon_archives_shadow_6156.png", dangerous=1, skill_list={298480,409283,409286,4092}, type=4, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[102]={ model="6156_z", name="Long Grass·Natural", english="DAVIST", story="Plants that used to grow widely in the Selevie Marsh, after being polluted, take on forms that disguise themselves as normal plants in the marsh, becoming highly aggressive once touched by any creatures.", hero_type=1, shadow="mon_archives_normal_6156.png", shadow_unlock="mon_archives_shadow_6156.png", dangerous=1, skill_list={298480,409583,409586,4095}, type=4, special="Focus Back Row", speed="", element={0}, weak_point={0,3}
},
	[103]={ model="6157", name="Axe Stag", english="DAVIST", story="Polluted tribal warriors that no longer resemble their original human form. Maybe they once had the power of [Deer Deity,] but now they're just [Mutant.] If you encounter them wandering in the wilderness, it's best to steer clear.", hero_type=5, shadow="mon_archives_normal_6157.png", shadow_unlock="mon_archives_shadow_6157.png", dangerous=2, skill_list={298880,409883,409886,4098,409801}, type=4, special="Focus Opposite Front Row", speed="", element={0}, weak_point={0,3}
},
	[104]={ model="6313", name="Deer Deity", english="DAVIST", story="Once a [god] of the Sleipnir tribe, a gigantic deer head exuding a dignified aura and terrifying pressure, worshipped by the people for generations. But now, it's merely a spirit confined in the wilderness.", hero_type=6, shadow="mon_archives_normal_6313.png", shadow_unlock="mon_archives_shadow_6313.png", dangerous=3, skill_list={410180,410190,410183,410186,4101,410101,410104}, type=4, special="Position Priority", speed="", element={0}, weak_point={1,4}
},
	[105]={ model="6158", name="Preacher", english="Alice", story="The ancient preacher of Vilatria, has lost himself over the long years, leaving only the instinct to pray to the gods for the power of the stars.", hero_type=1, shadow="mon_archives_normal_6158.png", shadow_unlock="mon_archives_shadow_6158.png", dangerous=1, skill_list={298380,410483,410486,4104}, type=3, special="Position Priority", speed="", element={0}, weak_point={0,3}
},
	[106]={ model="6159", name="Priest", english="DAVIST", story="Ancient priests of Vilatria, master the old celestial magic, almost without weakness. Whether in the past or now, getting involved with them is never a good idea.", hero_type=5, shadow="mon_archives_normal_6159.png", shadow_unlock="mon_archives_shadow_6159.png", dangerous=2, skill_list={298780,410783,410786,4107,410701}, type=3, special="Position Priority", speed="", element={0}, weak_point={0,3}
},
	[107]={ model="6314", name="Danica", english="DAVIST", story="The former captain of the Stellars Knights, once known as the [Angel of Vilatria,] has now been contaminated into a mutant. The glorious past has become a deeply buried secret, with only death bringing relief.", hero_type=6, shadow="mon_archives_normal_6314.png", shadow_unlock="mon_archives_shadow_6314.png", dangerous=3, skill_list={411080,411090,411083,411086,4110,411001,411004}, type=3, special="Position Focus Front Row", speed="", element={0}, weak_point={4,5}
},
	[108]={ model="6160", name="Corrupted Knight", english="DAVIST", story="The knights of Vilatria, master powerful lance techniques, almost without weakness. Whether in the past or now, getting involved with them is never a good idea.", hero_type=5, shadow="mon_archives_normal_6160.png", shadow_unlock="mon_archives_shadow_6160.png", dangerous=2, skill_list={411380,411383,411386,4113,411301}, type=3, special="Position Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[109]={ model="6315", name="Fragment of [Container]", english="DAVIST", story="The former captain of the Stellars Knights, once known as the [Angel of Vilatria,] has now been contaminated into a mutant. The glorious past has become a deeply buried secret, with only death bringing relief.", hero_type=6, shadow="mon_archives_normal_6315.png", shadow_unlock="mon_archives_shadow_6315.png", dangerous=3, skill_list={411680,411690,411683,411686,4116,411601,411604}, type=3, special="Position Priority", speed="", element={0}, weak_point={0,5}
},
	[110]={ model="6302_b", name="Sword Angel·Ice", english="DAVIST", story="A Shogger slightly resembling angels from ancient tales, attacking with a [great sword] made of the same material as its body. It appears to have intelligence, emitting rhythmical sounds from its [head.] Some say it's Shogger language but there's been no proof.", hero_type=6, shadow="mon_archives_normal_6302.png", shadow_unlock="mon_archives_shadow_6302.png", dangerous=3, skill_list={411980,411990,411983,411986,4119,411901,411904}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={2,5}
},
	[111]={ model="6304_h", name="Peril Beast·Fire", english="DAVIST", story="A creature from the alien species known as [Shogger] somewhat resembles a tiger from Taino Star, missing visible facial Feature but with a mouth that absorbs energy. Its four [tails] can emit energy and heat rays, causing great destruction. When attacked directly, it forms a protective barrier; breaking through requires much stronger force, making it one of the more troublesome Shogger types known.", hero_type=6, shadow="mon_archives_normal_6304.png", shadow_unlock="mon_archives_shadow_6304.png", dangerous=3, skill_list={412280,412290,412283,412286,4122,412201,412204}, type=4, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
},
	[112]={ model="6303_h", name="Scorpio·Fire", english="DAVIST", story="A Shogger individual shrouded in mystery, unlike common Shoggers, it not only shows intelligence but can also interfere with surrounding space to some extent. According to Leistance Security Bureau, this might be a high-level Shogger species, possibly even a leader, but specifics remain unclear.", hero_type=6, shadow="mon_archives_normal_6303.png", shadow_unlock="mon_archives_shadow_6303.png", dangerous=3, skill_list={412580,412590,412583,412586,4125,412501,412504}, type=4, special="Position Focus Front Row", speed="", element={0}, weak_point={3,4}
},
	[113]={ model="6142", name="[Defender]", english="DAVIST", story="The main battle mech invented during the Shogger invasion war, is praised for its durability, ease of production, and powerful firepower. Even a hundred years after the war, it still serves in various military and civilian forces on Taino. Due to its old model, it's sometimes jokingly referred to as [Big Daddy]", hero_type=5, shadow="mon_archives_normal_6142.png", shadow_unlock="mon_archives_shadow_6142.png", dangerous=2, skill_list={298680,412883,412886,4128,412801}, type=2, special="Focus Front Row", speed="", element={0}, weak_point={0,3}
}
}

return manual_mon_data