local story_data_30032=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=1001, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter03/prefab/30032_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="After the fight, Alicia didn't sheathe her blade. Instead, she knelt, examining each Mutant corpse.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="……", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Finally, she exhaled sharply, fists trembling.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Just like at the park… These were all civilians.", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="How could so many people vanish, turned into monsters, and Joshburg didn't even *notice*?!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=-1, abreast_id={8,10}, pType =2, cg_type =0, dialog=1, msg="Is Karanissa right? Is Joshburg really a city built on flesh and blood?!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=12, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Maybe.", msg_color="", msg_size=0, talker="Option 1", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=12, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Alicia…", msg_color="", msg_size=0, talker="Option 2", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="After a moment of silence, Alicia looked up—straight into the red glow of a surveillance device.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Jools Oke!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="You can't hide!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_311.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/common/prefab/StoryMask.prefab", runTalkTime =1000, destoryTime =3000, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Her furious shout carried through the device, reaching Jools' chamber undistorted.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_304.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=18, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Hide…? Hah. Hahahaha…", msg_color="", msg_size=0, talker="Jools", audio="", img="arts/ui/bg/story/storybg_304.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7132", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=19, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Central Council… Leistance… If you're breaking the peace, don't blame me for what comes next.", msg_color="", msg_size=0, talker="Jools", audio="", img="arts/ui/bg/story/storybg_304.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7132", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [19]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Behind Jools, amidst Void Particles dark as the abyss, an unseen horror slowly opened its eyes.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_304.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_30032
