local story_data_44314=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The last Mutant dissolved into Void Particles. Your tincture's effects were fading fast.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=1004, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="These abominations might've once been priests. Or Star Knights who defended Vilatria. Heroes, now reduced to guardians of secrets no one was meant to uncover.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This many Mutants weren't made overnight. Whoever left them here expected you to die.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=-1, abreast_id={5}, pType =2, cg_type =0, dialog=1, msg="Linker. Still breathing?", msg_color="", msg_size=0, talker="Centaurea", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2504", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=7, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Barely.", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2504", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=-1, abreast_id={8}, pType =2, cg_type =0, dialog=1, msg="We need to report this. Two people can't handle this mess. Who knows how many more are lurking.", msg_color="", msg_size=0, talker="Centaurea", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2504", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=10, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Agreed.", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2504", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="At this point, the how and why don't matter.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="If Void Particles leak further, this won't just be a tomb—it'll be Stardom's grave.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Centaurea helped you stagger back toward the tunnel. Neither of you noticed the eyes watching from the shadows—recording every moment.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_904.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_44314
