local story_data_40131=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=1002, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter04/prefab/40131_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Completely locked down. Heavy defenses.", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="If the Coordinator Sect's guarding this place, they must have an officer inside—", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="So? How do we break in?", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="…Maritimusr, let me be clear—we barely made it out alive last time.", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0},{ 3, "7135", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="If you want to back out now, this is your chance.", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0},{ 3, "7135", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="What, suddenly growing a conscience? Worrying about others?", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0},{ 3, "7135", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,0}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="…I just want to ask what they're planning. Maybe there's room to talk—", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0},{ 3, "7135", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Talk?! Are you insane?!", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This is my city. If I die, the whole dungeon suffers.", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7135", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="They might still give me some face, but you…", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7135", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="You're just passing through. No need to throw your lives away.", msg_color="", msg_size=0, talker="Ant King", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7135", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This city isn't yours.", msg_color="", msg_size=0, talker="Marianne", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7139", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="It's lawless land—everyone living here owns it.", msg_color="", msg_size=0, talker="Yanni", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7139", 2, 0},{ 3, "7140", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Well said, kid. Old man, stop flattering yourself. You saw those explosions—you really think they'll negotiate?", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="They'd shoot you on sight!", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=18, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="We're not here to save the city either. I'm not that noble—", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=19, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="But everyone has something they'll fight for.", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7129", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [19]={next_id=20, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="We need to storm in now. Void Particles concentration is rising—we have to control the valves immediately—", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [20]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Fine! Let's do this. Boys, we're going in!", msg_color="", msg_size=0, talker="Maritimus", audio="", img="arts/ui/bg/story/storybg_410.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0},{ 3, "7129", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_40131
