local story_data_10121=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=2, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter01/prefab/10081_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=-1, abreast_id={3}, pType =2, cg_type =0, dialog=1, msg="Two at the entrance. Unknown how many inside.", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=5, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Koraz takes the door.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="I'll handle the rest. Leave it to me.", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="No problem, meow~", msg_color="", msg_size=0, talker="Koraz", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0},{ 3, "2101_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="After exchanging glances, they rushed into the meeting room together—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0},{ 3, "2101_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Before the guards can react, Koraz disables them. Alicia slams the door open, bursting into the room—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=30, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_603.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/common/prefab/StoryMask.prefab", runTalkTime =1000, destoryTime =3000, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Nobody move!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_207.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_10121
