local story_data_100002=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=2, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG2.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {4}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Several days after returning from the desert, you submitted your report to HQ—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_10.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Though this mission was successfully completed per the Uzyantas government's request, you uncovered several suspicious points—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_10.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =5, dialog=1, msg="You discovered and confirmed—", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG2_1.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {8}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The power core of [Saladin] wasn't accidentally damaged but was restarted by some external force before being deliberately destroyed—", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="After the power core was destroyed, the leaked Stellar Crystal was influenced by the [Remnant's Wisdom],", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Reacting with the on-site Void Particles to form a Void Expanse, which brought forth the anchor and Shoggers...", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =5, dialog=1, msg="So...", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG2_2.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {12}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="What exactly is the [Remnant's Wisdom]?", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="After the incident, you spoke with the Remnants, but none of them knew what it was.", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Who gave this thing to them?", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =5, dialog=1, msg="……", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_10.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG2_3.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Who instigated the Remnants to restart and destroy the power core?", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_10.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [14]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This was the last sentence of your report.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_10.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   }
return story_data_100002
