local story_data_50121=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="Day 5, 13:41", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=1001, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter05/prefab/50121_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="When you three arrived at the rendezvous point, the Flying Fish Squad was locked in combat with the Mutants.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The girl with the heavy mechanical arms ripped open a hole in the Mutant siege. The girl piloting the giant gaming chair then launched missiles, blasting the horde apart.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="There's so many! Where are they even coming from?!", msg_color="", msg_size=0, talker="Gomia", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "1502_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Because the Void Particles concentration is getting higher. Anyone contaminated will turn into a Mutant...", msg_color="", msg_size=0, talker="Lilira", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "1502_h", 0, 0},{ 3, "1503_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Probably the entire underground of Lissugen has already become a Void Expanse...", msg_color="", msg_size=0, talker="Yuanya", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2501_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Where's Linker and the others? We've been waiting here too long—", msg_color="", msg_size=0, talker="Gomia", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 1, "1502_h", 0, 0},{ 2, "2501_h", 0, 0}}, model_pos={{ 0,0,0},{ 0.4,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 1,1},{ 2,0}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="We're here, meow!", msg_color="", msg_size=0, talker="Koraz", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="With Koraz's shout, you joined the battle.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_611.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "2101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_50121
