local story_data_101006=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="After confirming no anomalies remain in the Infeno ruins, you returned to the island in good spirits.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="1003", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Inside the decompression chamber, you debriefed Director Isis via remote comms.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Any notable findings from this operation?", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=-1, abreast_id={5,7}, pType =2, cg_type =10, dialog=1, msg="I want to hear your assessment first.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=9, abreast_id={}, pType =3, cg_type =10, dialog=1, msg="In some ways, Infeno was remarkable.", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,0}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=-1, abreast_id={}, pType =4, cg_type =10, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=9, abreast_id={}, pType =3, cg_type =10, dialog=1, msg="Yet it left us little of research value.", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,0}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=-1, abreast_id={}, pType =4, cg_type =10, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="That's your conclusion?", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Our analysts largely agree after reviewing your footage.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="That submerged city once housed humans. Then for some reason, Shoggers—or rather...", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="She paused, carefully choosing words before continuing.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,0}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="When Puruis fell, the city lost all external contact. After the last human died, it became purely mechanical ruins.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Their tragedy deserves mourning, but we must keep moving forward.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Rest well, Linker. Return to Leistance after recovery—I'll send Alicia to retrieve you.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Regarding the ruins, since they pose no threat and hold minimal value, we've voted to archive all data with Records Division.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=18, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Our priority remains combating active Shogger threats.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=19, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="We'll discuss next steps after your return.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [19]={next_id=20, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="Good work, 玩家名字.", msg_color="", msg_size=0, talker="Isis", audio="", img="arts/ui/bg/story/storybg_602.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "7110", 2, 1, 10, 204.5}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [20]={next_id=-1, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="— Ending Unlocked: [Sealed Discoveries]", msg_color="", msg_size=0, talker="", audio="", img="", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, page_show_effect={ 0.20, 0, 5, 0, 0.00, 0.00, 0.00, 0.00, 713.00, 341.00, 1.00, {}, {}}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_101006
