local story_data_60071=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="Day 5, 17:36", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=1001, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter06/prefab/60071_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Fierce winds howled at the tower's peak, as if wailing at the unfolding disaster.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="In the distance, the giant Scorpio strode through the city district, now several stories tall—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Each step caused surrounding skyscrapers to crumble, black-red vortices consuming everything.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Before you lay a crashed aircraft—and Flandre, smiling coyly.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Must you always ruin the mood~? Can't you just watch the show quietly like good spectators?", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Move! We don't have time for your madness!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0},{ 3, "3101_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Ara~ Why make impossible demands?", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0},{ 3, "3101_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Humans~ So blindly they demand from the earth. So blindly they demand from each other.", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="They crave. They explore. They seek to comprehend all they don't understand~", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="They believe they can understand everything. Believe they can explain everything.", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="They see no path forward, possess no true faith, lost in their struggles.", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="And we—we Coordinators—shall show them the way.", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="A faith to guide humanity eternally—", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Behold this magnificent sight! A god has descended! Shepherding His flock—", msg_color="", msg_size=0, talker="Flandre", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7126", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="You lunatic!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=18, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Alicia lost all patience with Flandre's ramblings and charged—but Yan moved faster—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Evil spirits! Be purged!", msg_color="", msg_size=0, talker="Yan", audio="", img="arts/ui/bg/story/storybg_607.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_60071
