local story_data_50101=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="Day 5, 12:40", msg_color="", msg_size=0, talker="", audio="", img="", video_url="", music_id=1001, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter05/prefab/50101_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Even if all Lissugen were drowning in Void Particles, this many Mutants couldn't emerge so quickly...", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Kyuren clearly intended to bury you here—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Or at least delay you past the point of no return.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=-1, abreast_id={6}, pType =2, cg_type =0, dialog=1, msg="Twenty minutes into the battle, maintaining dual AIMBS links left you lightheaded.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=8, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="(Should I activate deep link...?)", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Need a hand?", msg_color="", msg_size=0, talker="？？？", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="A familiar voice—from just two days prior—drifted over.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="With a flash of cold light, a figure charges into the fray.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="She swung invisible wires,reducing them to chunks in seconds—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Lycosha?!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=-1, abreast_id={14}, pType =2, cg_type =0, dialog=1, msg="Hi~", msg_color="", msg_size=0, talker="Lycosha", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=16, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="Why are you here…", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Hmm~ For fun?", msg_color="", msg_size=0, talker="Lycosha", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=-1, abreast_id={18}, pType =2, cg_type =0, dialog=1, msg="Let's slice these up first, then chat over tea?", msg_color="", msg_size=0, talker="Lycosha", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=-1, abreast_id={}, pType =3, cg_type =0, dialog=1, msg="...If you insist.", msg_color="", msg_size=0, talker="Option", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4107_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [19]={next_id=-1, abreast_id={}, pType =4, cg_type =0, dialog=1, msg="null", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_50101
