local story_data_44016=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="While you and Lionblade cleared that wave, another swarm slammed into Leoni's transport.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=1008, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Olivia moved like a hawk through the Mutants, her spear flashing—but one massive beast still rammed the minister's armored car.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="No—", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The vehicle flipped sideways. Two figures burst from the wreck.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Leoni and Lucas, guns blazing. Bullets peppered the Mutants, barely slowing their advance.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Leoni's face was grave, her gun never resting, yet the Mutants reached her, but at that moment the young cavalry reached her—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Professor—!!!", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/common/prefab/StoryHurt01.prefab", runTalkTime =400, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {10}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The black-haired girl firmly grabbed Leoni's hand and thrust back—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/common/prefab/StoryHurt01.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The spear deeply penetrated the Mutant's shell, Olivia used the momentum to propel, and the two dodged aside, avoiding the Mutant's attack.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Surviving vehicles screeched to their position.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Professor! Mr. Lucas! Get in—", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="...", msg_color="", msg_size=0, talker="Leoni", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Leoni didn't move immediately. Her gaze lingered on the overturned transport—now swarmed by Mutants.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7144", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Minister? We must—", msg_color="", msg_size=0, talker="Lucas", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Professor!", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "4108_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=18, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="...Understood.", msg_color="", msg_size=0, talker="Leoni", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7144", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [18]={next_id=19, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="She and Lucas boarded hastily. The convoy lurched forward again—but not before you and Lionblade caught Leoni's hesitation.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [19]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Seems the Foreign Minister's hiding more than she lets on.", msg_color="", msg_size=0, talker="Lionblade", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3102_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_44016
