local story_data_441514=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="空气中弥漫着焦黑的颜色，异变体在倒塌的房屋间奔走冲撞。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="60 69", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, page_show_effect={ 0.00, 0, 0, 0, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 1.00, {"rain", }, {}}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="天空飘着灰黑色的浊雨，劈里啪啦落在被虚粒子污染的大地上，空气中还弥漫着一股海水的腥臭味。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="梅德洛丝的手似乎更用力了一点。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="你回头，看着她仍旧闭着的双眼，停下了脚步。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="梅德洛丝，不要怕，睁开眼。", msg_color="", msg_size=0, talker="玩家名字", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="睁开眼……", msg_color="", msg_size=0, talker="梅德洛丝", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={{ 2, "4527", 0, 0, 28.5, 221}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, model_show_effect={{}}, update_model={{ 2,1}}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="一阵哭泣声打断了你们。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="妈妈……", msg_color="", msg_size=0, talker="小女孩", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="梅德洛丝僵住了。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="你看向那个方向，正在哭泣的小女孩身上披着一件布满油污的围裙，在那儿声嘶力竭地哭喊着。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="她前方不远处，一位中年妇女一手捏着做饭的厨刀，另一手提着一篮生肉，正在拼命对着一头怪物比划。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="来呀怪东西，你看这边！", msg_color="", msg_size=0, talker="中年妇女", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="血迹和雨水顺着她油渍斑斑的衣服往下淌，她的头发黏糊糊贴在额头上，表情要比怪物还要狰狞。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="怪东西哈哈！", msg_color="", msg_size=0, talker="中年妇女", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="她的动作看起来滑稽可笑，怪物也确实被她吸引了。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=17, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="吼！", msg_color="", msg_size=0, talker="怪物", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [17]={next_id=-1, abreast_id={}, pType =1, cg_type =10, dialog=1, msg="梅德洛丝脸色猛然变了。", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_9_101.jpg", video_url="", music_id="0", background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, model_show_effect={}, update_model={}, role_act={}, head_path="", shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_441514
