local story_data_100001=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=2, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG3.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {4}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The day after returning from the desert, you submitted your report to HQ—", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Below was an excerpt from your report:", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =5, dialog=1, msg="...", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG3_1.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {9}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="In conclusion, I believe this incident was caused by Remnants entering the battleship to collect supplies and accidentally damaging the power core.", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The leaked Stellar Crystal was mutated by Void Particles.", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="And eventually forming a Void Expanse due to excessive Void Particle concentration, summoning the anchor and Shoggers.", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="……", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_16.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =5, dialog=1, msg="Though some questions remain unanswered, the overall situation is under control.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_16.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/infinitecity/prefab/infinitecityCG3_2.prefab", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The Uzyanta government will handle the remaining cleanup.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_16.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   [11]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This investigation is thus concluded.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/cycle/Collectibles_bg_16.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, waitIDs = {}},
   }
return story_data_100001
