local story_data_10141=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="", msg_color="", msg_size=0, talker="", audio="", img="arts/storyPrefab/prefab/common/texture/black.png", video_url="", music_id=3, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter01/prefab/10101_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="玩家名字… something's… off…", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="This isn't… normal Void Particles anomaly...", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Pain…meow…", msg_color="", msg_size=0, talker="Koraz", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0},{ 3, "2101_h", 0, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="—!", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="—", msg_color="", msg_size=0, talker="Alicia", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "3101_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Their voices distort, fading beneath your own heartbeat.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Fear—long forgotten—crawls up your spine.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="From the [door], a [creature] slithers into reality.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="…", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "6107", 1, 0}}, model_pos={{ 0,0,2}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="!?!?", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "6107", 1, 0}}, model_pos={{ 0,0,2}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "6107", 1, 0}}, model_pos={{ 0,0,2}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=40, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The [creature] sees you and charges at you.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=15, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="In that instant, you remember. The [door]. The creature.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [15]={next_id=16, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The legendary calamities: an Anchor.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [16]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Shogger.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_302.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_10141
