local story_data_44002=
{
   [1]={next_id=2, abreast_id={}, pType =1, cg_type =5, dialog=0, msg="08:13, Urban Street, Lissugen.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=1001, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="arts/storyPrefab/prefab/chapter1.1/prefab/44002_BGpan.prefab", runTalkTime =3500, destoryTime =4500, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [2]={next_id=3, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The convoy, unloaded from the airship, sped through Void Particle-infested streets.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [3]={next_id=4, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Braking sounds—", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [4]={next_id=5, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The vehicles slammed to a halt.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={}, model_pos={}, model_move_pos={}, model_exit={}, update_model={}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [5]={next_id=6, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Sir, Void Particle density ahead is critical. Heavy Mutant presence.", msg_color="", msg_size=0, talker="Lucas", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [6]={next_id=7, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Any detours?", msg_color="", msg_size=0, talker="Leoni", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [7]={next_id=8, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="None. This is the clearest route.", msg_color="", msg_size=0, talker="Lucas", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,0}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [8]={next_id=9, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="The situation's worse than expected... We must reach the embassy.", msg_color="", msg_size=0, talker="Leoni", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [9]={next_id=10, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Our vehicles lack heavy weapons. Ramming through isn't an option.", msg_color="", msg_size=0, talker="Lucas", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1},{ 3,0}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [10]={next_id=11, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="A dark-haired girl stepped forward.", msg_color="", msg_size=0, talker="", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7145", 2, 0},{ 3, "7144", 2, 0}}, model_pos={{ 0,0,0},{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,0},{ 3,0}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [11]={next_id=12, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Professor, let me handle this.", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [12]={next_id=13, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Olivia?", msg_color="", msg_size=0, talker="Leoni", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "7144", 2, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [13]={next_id=14, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Heh. I know why I'm here—for moments like this.", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   [14]={next_id=-1, abreast_id={}, pType =1, cg_type =0, dialog=1, msg="Don't worry. I'll clear the path!", msg_color="", msg_size=0, talker="Olivia", audio="", img="arts/ui/bg/story/storybg_507.jpg", video_url="", music_id=0, background_music="", model_tid={{ 2, "4108_h", 0, 0}}, model_pos={{ 0,0,0}}, model_move_pos={}, model_exit={}, update_model={{ 2,1}}, role_act={}, head_path="", flash_time=0, shake_ani=0, grad_time=0, is_memory=0, roll_str="",roll_bg ="", static_pic ="", prefab_path ="", runTalkTime =0, destoryTime =0, clickTimes =0, effPos={ 0,0,0},effUrl="", waitIDs = {}},
   }
return story_data_44002
