--[[
-----------------------------------------------------
@filename       : FuncOpenConst
@Description    : 功能开放常量
@date           : 2020-10-19 16:32:39
@Author         : Jacob
@copyright      : (LY) 2020 雷焰网络
-----------------------------------------------------
]]
module('game.funcopen.manager.FuncOpenConst', Class.impl())

-- 主界面-冒险
FUNC_ID_ADVENTURE = 1
-- 主界面-竞技(入口控制)
FUNC_ID_PVP = 2
-- 主界面-日常
FUNC_ID_TASK = 3
-- 主界面-招募
FUNC_ID_RECRUIT = 4
-- 主界面-战员
FUNC_ID_HERO = 5
-- 主界面-背包
FUNC_ID_BAG = 6
-- 主界面-好友
FUNC_ID_FRIEND = 7
-- 主界面-商店
FUNC_ID_STOP = 8
-- 主界面-邮件
FUNC_ID_MAIL = 9
-- 主界面-公告
FUNC_ID_BULLETIN = 10
-- 主界面-个人主页
FUNC_ID_HOME = 11
-- 主界面-聊天
FUNC_ID_CHAT = 12
-- 主界面-体力购买
FUNC_ID_ADDSTAMINA = 13
-- 主界面-金币购买
FUNC_ID_CONVERT = 14
-- 主界面-福利
FUNC_ID_HOME_WELFARE = 15
-- 主界面-无限城
FUNC_ID_INFINITE_CITY = 16

-- 主界面-盟约
FUNC_ID_COVENANT = 18
-- 主界面-训练
FUNC_ID_TRAINING = 19

--主界面-新手目标
FUNC_ID_ACTIVITY_TARGET = 20
-- 主界面-宿舍
FUNC_ID_DORMITORY = 21

-- 主界面-购买
FUNC_ID_PURCHASE = 22

-- 主界面-通行证
FUNC_ID_PERMIT = 23
-- 主界面-档案界面
FUNC_ID_MANUAL = 25
-- 主界面-肉鸽
FUNC_ID_ROGUE = 26
-- 主界面-迷你工厂
FUNC_ID_MINIFACTORY = 27
-- 主界面-设置
FUNC_ID_SETTING = 28
-- 锚驴
FUNC_ID_PET = 29
-- 主界面-成长基金
FUNC_ID_GROWTHFUND = 31
-- 基建
FUNC_ID_WARSHIP = 32
-- 手环通讯
FUNC_ID_COMMUNICATION = 33
-- 活动
FUNC_ID_ACTIVITY = 34
-- 交易所
FUNC_ID_SHOPPING = 35
-- 主界面-首充
FUNC_ID_FIRSTCHARGE = 36

--新人活动
FUNC_ID_NOVICE_ACTIVITY = 38
--节日福利
FUNC_ID_FESTIVAL = 39
--联盟
FUNC_ID_GUILD = 40

--回归活动
FUNC_ID_RETURNED = 41

--主界面-时装通行证
FUNC_ID_FASHIONPERMIT = 42
--主界面-总力战
FUNC_ID_DISASTER = 43
-- 主界面-周年庆
FUNC_ID_CELEBRATION = 44

--主界面-时装通行证
FUNC_ID_FASHIONPERMITTWO = 45

--主界面-特供
FUNC_ID_SPECIALSUPPLY = 46

-- 简单界面
FUNC_ID_SIMPLE = 48
-- 战斗界面
FUNC_ID_FIGHT_SPEED = 50
-- 战斗界面-自动/手动
FUNC_ID_FIGHT_AUTO = 51
-- 战斗界面-设置
FUNC_ID_FIGHT_SETTING = 52
-- 战斗界面-格挡
FUNC_ID_FIGHT_ABBLOCK = 53
-- 战斗界面-buff详情
FUNC_ID_FIGHT_BUFF_INFO = 54

-- 冒险-主线
FUNC_ID_MAINMAP = 101
-- 冒险-行动
FUNC_ID_DUP_DAILY = 102
-- 冒险-挑战
FUNC_ID_CHALLENGE = 103
-- 冒险-支线
FUNC_ID_BRANCH_STORY = 104
-- 冒险-战员传记
FUNC_ID_BIOGRAPHY = 105
-- 冒险-芯片
FUNC_ID_EQUIP = 106
-- 冒险-特殊关卡
FUNC_ID_SPECIAL = 107
-- 冒险-攻坚关卡
FUNC_ID_SUPER_SPECIAL = 108
-- 资源本多倍挑战
FUNC_ID_DUP_MULTI = 111
-- 支线关卡
FUNC_ID_FRAGMENTMAP = 112

-- 支线-备战试炼
FUNC_ID_BRANCH_STORY_EQUIP = 151
-- 支线-战场异闻
FUNC_ID_BRANCH_STORY_MAIN = 152
-- 支线-战术训练
FUNC_ID_BRANCH_STORY_TACTIVS = 153
-- 支线-能源力场
FUNC_ID_BRANCH_POWER = 154

-- 竞技-竞技场(面板控制)
FUNC_ID_PVP_ARENA = 201

--巅峰竞技场
FUNC_ID_PVP_ARENA_HELL = 202

--星夜漫步
FUNC_ID_RAFFLE = 211
-- 日常-日常
FUNC_ID_TASK_DAILY = 301
-- 日常-周常
FUNC_ID_TASK_WEEK = 302

-- 招募-高级招募
FUNC_ID_RECRUIT_SUPER = 401
-- 招募-普通招募
FUNC_ID_RECRUIT_NOMAL = 402
-- 招募-新手招募
FUNC_ID_RECRUIT_NEW_PLAYER = 403
-- 招募-手环研发
FUNC_ID_RECRUIT_BRACELETS = 404

-- 招募-战员遣散
--FUNC_ID_HERO_DISMISS = 407

-- 战员-编队
FUNC_ID_HERO_TEAM = 501
-- 战员-培养
FUNC_ID_HERO_CULTURE = 502
-- 战员-编队第一队列后面的使用开启条件
FUNC_ID_HERO_EXCEPT_FIRST_TEAM = 503

-- 战员-编队移动
FUNC_ID_FORMATION_MOVE = 504

-- 背包-分解
FUNC_ID_BAG_BREAK = 601

--背包-材料(战员情报)
FUNC_ID_HERO_FRAGMENT = 602

--背包-芯片
FUNC_ID_EQUIP = 603

--背包-手环
FUNC_ID_BRACELETS = 604

--背包-消耗物质
FUNC_ID_CONSUME = 605

-- 背包-原料
FUNC_ID_BAG_RAWMAT = 606

-- 好友-发现
FUNC_ID_FRIEND_RECOMMEND = 701
-- 好友-申请
FUNC_ID_FRIEND_APPLY = 702
-- 好友-私聊
FUNC_ID_FRIEND_CHAT = 703

-- 商店-交易所
FUNC_ID_STOP_NOMAL = 801
-- 商店-军械所
FUNC_ID_STOP_ARM = 802
-- 商店-黑市
FUNC_ID_STOP_BLACK = 803
-- 商店-兑换
FUNC_ID_STOP_CONVERT = 804
-- 商店-元件
FUNC_ID_STOP_DISMISS = 805
-- 商店-碎片
FUNC_ID_STOP_FRAGMENTS = 806
-- 商店-宿舍
FUNC_ID_STOP_DORMOTORY = 809
-- 商店-模组
FUNC_ID_STOP_EQUIP = 810
--商店--巅峰竞技场
FUNC_ID_STOP_ARENA_HELL = 811

-- 问卷调查
FUNC_ID_SURVEY_WEBVIEW = 1001

-- 个人主页-头像
FUNC_ID_HOME_HEAD = 1101
-- 个人主页-成就
FUNC_ID_HOME_ACHIEVEMENT = 1102
-- 个人主页-头像框
FUNC_ID_HOME_HEAD_FRAME = 1103
-- 个人主页-称号
FUNC_ID_HOME_TITLE = 1104

-- 个人主页-背景
FUNC_ID_HOME_BACKGROUND = 1106

-- 个人主页- 助理组
FUNC_ID_HERO_GURAD_GROUP = 1107

-- 主界面-签到
FUNC_ID_HOME_SIGNIN = 1501

-- 福利 战斗补给
FUNC_ID_WELFAREOPT_FIGHT = 1502
-- 福利 金币祈愿
FUNC_ID_WELFAREOPT_GOLDWSHING = 1503
-- 福利 7天登录
FUNC_ID_WELFATEOPT_SEVENDAY = 1504
-- 福利 体力补给
FUNC_ID_WELFATEOPT_STRENGTH = 1505
-- 福利 新人训练营
FUNC_ID_WELFAREOPT_NOVICETRAIN = 1506
-- 福利 七天目标
FUNC_ID_WELFAREOPT_SEVENDAY_TARGET = 1507
-- 福利 公测福利
FUNC_ID_WELFAREOPT_OPEN_BETA = 1508
-- 福利 抽奖
FUNC_ID_WELFAREOPT_RAFFLE = 1509

--福利 TAPTAP
FUNC_ID_WELFAREOPT_TAPTAP = 1510

-- 盟约-研究所
FUNC_ID_COVENANT_GRADUATE_SCHOOL = 1801
-- 盟约-总部
FUNC_ID_COVENANT_HEAD_QUARTER = 1802
-- 盟约-科技树
FUNC_ID_COVENANT_SCIENCE_TREE = 1803

--盟约-任务
FUNC_ID_COVENANT_TASK = 1808

-- 购买——直购礼包
FUNC_ID_PURCHASE_DIRECT_BUY = 1901
-- 购买——月卡
FUNC_ID_PURCHASE_MONTH_CARD = 1902
-- 购买——充值
FUNC_ID_PURCHASE_RECHARGE = 1903
-- 购买——皮肤商店
FUNC_ID_SKIN_SHOP = 1904
-- 购买——等级礼包
FUNC_ID_GRADE_GIFT = 1905
-- 购买——时装币商店
FUNC_ID_FASHIONCION_SHOP = 1906
-- 购买——体力月卡
FUNC_ID_STRENGTH_CARD = 1907
-- 购买——神血月卡
FUNC_ID_BLOOD_CARD = 1999

-- 战员时装-展示界面
FUNC_ID_HERO_FASHION_SHOW = 1908
-- 商店-限时礼包充值
FUNC_ID_SHOP_LIMIT_GIFT = 1909

--阿尔戈特供
FUNC_ID_SUPECIAL = 1910

-- 档案——怪物
FUNC_ID_MANUAL_MONSTER = 2001
-- 档案——音乐
FUNC_ID_MANUAL_MUSIC = 2002
-- 档案——模组
FUNC_ID_MANUAL_MODULD = 2003
-- 档案——烙痕
FUNC_ID_MANUAL_SOLDERINGMARK = 2004
-- 档案——故事
FUNC_ID_MANUAL_STORY = 2005
-- 档案——世界
FUNC_ID_MANUAL_WORLD = 2006
-- 档案——战员
FUNC_ID_MANUAL_HERO = 2007

-- 迷你工厂——原料
FUNC_ID_FACTORY_RAWMAT = 2011

-- 迷你工厂——物资
FUNC_ID_FACTORY_MATERIAL = 2011

-- 迷你工厂——芯片
FUNC_ID_FACTORY_CHIP = 2012

-- 迷你工厂——礼物
FUNC_ID_FACTORY_GIFT = 2013

-- 迷你工厂——盟约
FUNC_ID_FACTORY_COVENANT = 2014

--1.1活动主界面
FUNC_ID_MAIN_ACTIVITY = 2101
--2.2小游戏-整理背包
FUNC_ID_ORGANIZE_BACKPACKS = 2120
--活动剧情档案
FUNC_ID_MANUAL_ACTIVITY = 2501

--新手活动- 关注关注有奖励
FUNC_ID_ACTIVITY_SUBSCRIBE = 3401
--新手活动- 投资理财
FUNC_ID_ACTIVITY_INVEST = 4603--活动
--特供-自选礼包
FUNC_ID_ACTIVITY_SELECT_BUY = 4604
--特供-限时活动—限时任务完成送体力月卡
FUNC_ID_ACTIVITY_STRENGTH_TASK = 4699
-- 充值好礼
FUNC_ID_ACTIVITY_RECHARGE_NICE_GIFT = 4601--新手活动
-- 夏日促销礼包
FUNC_ID_ACTIVITY_SUMMER_RECHARGE_GIFT = 4650
-- 投资理财
FUNC_ID_FACTORY_NOVICEACTIVITY_RECRUIT = 3801
--新手活动-累计铸痕
FUNC_ID_FACTORY_NOVICEACTIVITY_BRACELECTS = 3802
--新手活动-升格计划
FUNC_ID_FACTORY_NOVICEACTIVITY_UPGRADEPLAN = 3803


--新手活动-升级返回
FUNC_ID_NOVICEACTIVITY_RETURN = 3804
--新手活动-抽奖
FUNC_ID_NOVICEACTIVITY_RAFFLE = 3805

--新手活动 邀请函
FUNC_ID_NOVICEACTIVITY_SSR = 3806
--新手活动 累计充值
FUNC_ID_NOVICEACTIVITY_RECHARGE = 3807

--周年庆典-SSR月卡自选
FUNC_ID_SSR_OPTIONAL = 4401
--周年庆典--庆典任务
FUNC_ID_CELEBRATION_TASK = 4402
--周年庆典--庆典累充
FUNC_ID_CELEBRATION_ACC_RECHARGE = 4403
--新年活动--抽奖
FUNC_ID_NEWYEAR_ROUNDPRIZE = 4404
--新年活动--抽奖2
FUNC_ID_NEWYEAR_ROUNDPRIZE_TWO = 4405
--两周年超级礼包
FUNC_ID_ACTIVITY_SUPER_GIFT = 4406

--特供--狂欢好礼
FUNC_ID_CARNIVAL_GIFT = 4602
--特供--狂欢好礼2
FUNC_ID_CARNIVAL_GIFT2 = 4602
-- 战员培养-升级
FUNC_ID_HERO_LV_UP = 50201
-- 战员培养-技能
FUNC_ID_HERO_SKILL = 50202
-- 战员培养-进化
FUNC_ID_HERO_STAR = 50203
-- 战员培养-芯片
FUNC_ID_HERO_EQUIP = 50204
-- 战员培养-芯片强化
FUNC_ID_HERO_EQUIP_STRENGTHEN = 50205
-- 战员培养-芯片改造
FUNC_ID_HERO_EQUIP_RETROFIT = 50206
-- 战员培养-芯片重构
FUNC_ID_HERO_EQUIP_REFACTOR = 50207
-- 战员培养-芯片基础属性
FUNC_ID_HERO_EQUIP_ATTR = 50208

-- 战员培养-升品
FUNC_ID_HERO_COLOR_UP = 50209
-- 战员培养-手环
FUNC_ID_HERO_BRACELETS = 50210
-- 战员培养-手环强化
FUNC_ID_HERO_BRACELETS_STRENGTHEN = 50211
-- 战员培养-手环精炼
FUNC_ID_HERO_BRACELETS_REFINE = 50212
-- 战员培养-手环赋能
FUNC_ID_HERO_BRACELETS_EMPOWER = 50221

-- 战员培养-模組改造(新)
FUNC_ID_HERO_BRACELETS_REMOLD = 50224

-- 战员培养-共鸣
FUNC_ID_HERO_RESONANCE = 50222


-- 战员亲密度
FUNC_ID_FAVORABLE = 50214
-- 战员培养-增幅
FUNC_ID_HERO_GROW = 50215
-- 战员时装
FUNC_ID_HERO_FASHION = 50213
-- 战员助战
FUNC_ID_HERO_ASSIST = 50216
-- 战员速升
FUNC_ID_FAST_LVUP = 50217
-- 战员时装-服饰
FUNC_ID_HERO_FASHION_CLOTHES = 502131
-- 战员时装-武器
FUNC_ID_HERO_FASHION_WEAPON = 502132

-- 行动-瓦斯坦金矿
FUNC_ID_DUP_MONEY = 10201
-- 行动-全息训练
FUNC_ID_DUP_EXP = 10202
-- 行动-麦瑟奎德工厂
FUNC_ID_DUP_EQUIP = 10203
-- 行动-塞米肯加工厂
FUNC_ID_DUP_EQUIP_TUPO = 10204
-- 行动-手环培养副本
FUNC_ID_DUP_BRACELETS = 10211
-- 行动-战员晋升副本
FUNC_ID_DUP_HERO_STAR_UP = 10212
-- 行动-战员增幅副本
FUNC_ID_DUP_HERO_GROW_UP = 10213
-- 手环升级副本
FUNC_ID_DUP_BRACELET_UP = 10215
-- 手环突破副本
FUNC_ID_DUP_BRACELET_EVOLVE = 10216
-- 潜能副本-直击强化
FUNC_ID_DUP_ATTACKHARDENING_POTENCY = 10217
-- 潜能副本-驰电畸点
FUNC_ID_DUP_ELECTRIC_POTENCY = 10218
-- 潜能副本-轰炎
FUNC_ID_DUP_FIRE_POTENCY = 10219
-- 潜能副本-寒霜
FUNC_ID_DUP_ICE_POTENCY = 10220
-- 潜能副本-生蕴
FUNC_ID_DUP_LIFE_POTENCY = 10221
-- 潜能副本-量蚀
FUNC_ID_DUP_CAVITATION_POTENCY = 10222
-- 潜能副本-直击强化（难度2）
FUNC_ID_DUP_ATTACKHARDENING_POTENCY_2 = 10223
-- 潜能副本-驰电畸点（难度2）
FUNC_ID_DUP_ELECTRIC_POTENCY_2 = 10224
-- 潜能副本-轰炎（难度2）
FUNC_ID_DUP_FIRE_POTENCY_2 = 10225
-- 潜能副本-寒霜（难度2）
FUNC_ID_DUP_ICE_POTENCY_2 = 10226
-- 潜能副本-生蕴（难度2）
FUNC_ID_DUP_LIFE_POTENCY_2 = 10227
-- 潜能副本-量蚀（难度2）
FUNC_ID_DUP_CAVITATION_POTENCY_2 = 10228
-- 潜能副本-直击强化（难度3）
FUNC_ID_DUP_ATTACKHARDENING_POTENCY_3 = 10229
-- 潜能副本-驰电畸点（难度3）
FUNC_ID_DUP_ELECTRIC_POTENCY_3 = 10230
-- 潜能副本-轰炎（难度3）
FUNC_ID_DUP_FIRE_POTENCY_3 = 10231
-- 潜能副本-寒霜（难度3）
FUNC_ID_DUP_ICE_POTENCY_3 = 10232
-- 潜能副本-生蕴（难度3）
FUNC_ID_DUP_LIFE_POTENCY_3 = 10233
-- 潜能副本-量蚀（难度3）
FUNC_ID_DUP_CAVITATION_POTENCY_3 = 10234

-- 挑战-识域勘探
FUNC_ID_CHELLENGE_TOWER = 10301
-- 挑战-代号·希望
FUNC_ID_CODE_HOPE = 10302
-- 挑战-默示之境
FUNC_ID_IMPLIED = 10303
-- 挑战-移动迷宫
FUNC_ID_MAZE = 10304
-- 挑战-使徒之战
FUNC_ID_APOSTLE_WAR = 10305
-- 挑战-使徒之战2
FUNC_ID_APOSTLE2_WAR = 10306
-- 挑战-元素塔
FUNC_ID_DUP_ELEMENT = 10307
-- 挑战-无限城
FUNC_ID_CYCLE = 10308

FUNC_ID_BOUNDLESS = 10309

--挑战-海底
FUNC_ID_SEADED = 10310

-- 模组掉落选择
FUNC_ID_DUPCHIP_DROPSELECT = 10602

--战员蛋
FUNC_ID_HERO_EGG = 50227

--切换cv
FUNC_ID_SWITCH_CV = 1109

return _M

--[[ 替换语言包自动生成，请勿修改！
]]
